import { describe,expect,test } from "@jest/globals";import { readFileSync } from "node:fs";import path from "node:path";
const block=readFileSync(path.resolve(__dirname,"../CircleReachBlock.tsx"),"utf8"),sheet=readFileSync(path.resolve(__dirname,"../CircleReachSheet.tsx"),"utf8");
describe("#1777 Circle UI contract",()=>{
  test("rows are static, safe, and preview is capped at three",()=>{expect(block).toContain("CIRCLE_PREVIEW_LIMIT=3");expect(block).toContain("accessibilityRole=\"text\"");expect(block).not.toMatch(/Pressable|onPress=\{onPress\}|email|phone|contact|event|connector/i)});
  test("exact states and full sheet controls remain available",()=>{for(const copy of ["Checking current reach…","No followers to show yet.","No one is in your extended circle yet.","Extended circle isn’t available yet.","Reach is temporarily unavailable.","You’re offline. Connect to check current reach.","Couldn’t load more people.","Loading more people…"])expect(block+sheet).toContain(copy);expect(sheet).toContain('snapPoint="full"');expect(sheet).toContain('accessibilityViewIsModal');expect(sheet).toContain('label="Load more"')});
  test("moves focus into the modal and contains keyboard focus",()=>{expect(sheet).toContain("closeRef.current");expect(sheet).toContain("AccessibilityInfo.setAccessibilityFocus");expect(sheet).toContain('event.key!=="Tab"');expect(sheet).toContain('event.key==="Escape"');expect(sheet).toContain('document.addEventListener("keydown",onKeyDown)')});
  test("reduced motion renders identities immediately and retry preserves the failure body",()=>{expect(block).toContain("useReducedMotionNative()");expect(block).toContain("if(reduceMotion){fade.setValue(1);return}");for(const source of [block,sheet]){expect(source).toContain('loading={retrying}');expect(source).toContain('disabled={retrying}');expect(source).toContain('setRetrying(true)');expect(source).toContain('setRetrying(false)')}expect(block).toContain('const loading=!retrying&&');expect(sheet).toContain('!retrying&&["loading","refreshing","cursorRefreshing"]')});
  test("forbids search, selection, campaign, and contact affordances",()=>{for(const forbidden of ['label="Search"','label="Select"','label="New campaign"','label="Export"','label="Copy"','email','phone','contactValue'])expect(block+sheet).not.toContain(forbidden)});
});
