/**
 * Global search — the static Feature / Settings findability registry.
 *
 * META-ORCH-1073 Sub-A. SPEC §3.5 (LOCKED contents/routes/minRanks/synonyms)
 * + §12.1 R-3 (STANDALONE-SCREEN-ONLY: keep ONLY entries that deep-link to a
 * real standalone screen). Icons from DESIGN §9.1 (all in the `IconName` set).
 *
 * EVERY `route` below MUST exist in `app/` — see registry-routes assertion in
 * globalSearch.test.ts. If a screen is renamed/removed, that test fails. The
 * `:brandId` placeholder is substituted with the current brand id at index
 * build (buildSearchIndex); entries that still contain `:brandId` when no
 * brand is loaded are dropped (can't deep-link without an id).
 *
 * R-3 trim result (META-ORCH-1073 Sub-A): all 27 SPEC §3.5 entries deep-link
 * to a real standalone `app/` screen (verified against the route tree), so
 * ZERO entries were dropped. Per-entity actions that would need event+order
 * context (e.g. "issue this refund") were never in the §3.5 set — those
 * return via the Money sub-ORCH as contextual/per-list actions.
 *
 * `minRank` uses BRAND_ROLE_RANK (scanner 10, marketing_manager 20,
 * finance_manager 30, event_manager 40, brand_admin 50, brand_owner 60).
 */

import type { SearchRegistryItem } from "./types";

/** Placeholder substituted with the current brand id at index build. */
export const BRAND_ID_TOKEN = ":brandId";

export const FEATURE_REGISTRY: readonly SearchRegistryItem[] = [
  // ---- Group `goto` — navigable top-level screens -----------------------
  {
    key: "home",
    type: "screen",
    title: "Home",
    subtitle: "Your dashboard at a glance",
    route: "/(tabs)/home",
    group: "goto",
    minRank: 10,
    synonyms: ["dashboard", "start", "overview"],
    iconName: "home",
  },
  {
    key: "hub-events",
    type: "screen",
    title: "Events",
    subtitle: "All your events",
    route: "/(tabs)/hub/events",
    group: "goto",
    minRank: 10,
    synonyms: ["my events", "listings", "shows"],
    iconName: "calendar",
  },
  {
    key: "hub-trips",
    type: "screen",
    title: "Trips",
    subtitle: "All your trips",
    route: "/(tabs)/hub/trips",
    group: "goto",
    minRank: 10,
    synonyms: ["tours", "getaways", "retreats"],
    iconName: "compass",
  },
  {
    key: "hub-experiences",
    type: "screen",
    title: "Experiences",
    subtitle: "All your experiences",
    route: "/(tabs)/hub/experiences",
    group: "goto",
    minRank: 10,
    synonyms: ["activities", "things to do"],
    iconName: "sparkle",
  },
  {
    key: "marketing-overview",
    type: "screen",
    title: "Marketing",
    subtitle: "Reach your buyers",
    route: "/(tabs)/marketing",
    group: "goto",
    minRank: 20,
    synonyms: ["promote", "blasts", "growth"],
    iconName: "trending",
  },
  {
    key: "marketing-campaigns",
    type: "screen",
    title: "Campaigns",
    subtitle: "Send an email blast",
    route: "/(tabs)/marketing/campaigns",
    group: "goto",
    minRank: 20,
    synonyms: ["email", "blast", "send"],
    iconName: "mail",
  },
  {
    key: "marketing-audiences",
    type: "screen",
    title: "Audiences",
    subtitle: "Your contact lists",
    route: "/(tabs)/marketing/audiences",
    group: "goto",
    minRank: 20,
    synonyms: ["lists", "contacts", "segments"],
    iconName: "users",
  },
  {
    key: "marketing-templates",
    type: "screen",
    title: "Templates",
    subtitle: "Reusable email designs",
    route: "/(tabs)/marketing/templates",
    group: "goto",
    minRank: 20,
    synonyms: ["email template", "designs"],
    iconName: "template",
  },
  {
    key: "account",
    type: "screen",
    title: "Account",
    subtitle: "Your profile and settings",
    route: "/(tabs)/account",
    group: "goto",
    minRank: 10,
    synonyms: ["profile", "me", "my account"],
    iconName: "user",
  },
  {
    key: "brand-public-listing",
    type: "screen",
    title: "Public page",
    subtitle: "How buyers see your brand",
    route: `/brand/${BRAND_ID_TOKEN}/listing`,
    group: "goto",
    minRank: 20,
    synonyms: ["public profile", "my page", "brand page"],
    iconName: "globe",
  },
  // ---- Group `goto` — brand sub-screens ---------------------------------
  {
    key: "brand-edit",
    type: "screen",
    title: "Edit brand",
    subtitle: "Name, bio, logo and socials",
    route: `/brand/${BRAND_ID_TOKEN}/edit`,
    group: "goto",
    minRank: 20,
    synonyms: ["brand profile", "bio", "logo", "brand name", "socials"],
    iconName: "edit",
  },
  {
    key: "brand-team",
    type: "screen",
    title: "Team",
    subtitle: "Members, roles and permissions",
    route: `/brand/${BRAND_ID_TOKEN}/team`,
    group: "goto",
    minRank: 50,
    synonyms: ["members", "staff", "invite", "roles", "permissions"],
    iconName: "users",
  },
  {
    key: "brand-scanners",
    type: "screen",
    title: "Scanners",
    subtitle: "Door staff who check tickets",
    route: `/brand/${BRAND_ID_TOKEN}/scanners`,
    group: "goto",
    minRank: 40,
    synonyms: ["invite scanner", "door staff", "check-in", "ticket scanner"],
    iconName: "scan",
  },
  {
    key: "brand-audit-log",
    type: "screen",
    title: "Audit log",
    subtitle: "History of changes",
    route: `/brand/${BRAND_ID_TOKEN}/audit-log`,
    group: "goto",
    minRank: 50,
    synonyms: ["history", "activity", "changes", "log"],
    iconName: "notebook",
  },
  {
    key: "brand-blasts",
    type: "screen",
    title: "Brand blasts",
    subtitle: "Announcements to your followers",
    route: `/brand/${BRAND_ID_TOKEN}/blasts`,
    group: "goto",
    minRank: 20,
    synonyms: ["brand email", "announcements"],
    iconName: "send",
  },
  // ---- Group `settings` — settings & actions ----------------------------
  {
    key: "payments",
    type: "setting",
    title: "Payments & Bank",
    subtitle: "Bank, payouts and payments",
    route: `/brand/${BRAND_ID_TOKEN}/payments`,
    group: "settings",
    minRank: 30,
    synonyms: ["stripe", "bank", "connect", "payout setup", "get paid"],
    iconName: "bank",
  },
  {
    key: "payments-onboard",
    type: "action",
    title: "Set up payouts",
    subtitle: "Connect your bank to get paid",
    route: `/brand/${BRAND_ID_TOKEN}/payments/onboard`,
    group: "settings",
    minRank: 30,
    synonyms: ["onboarding", "connect stripe", "verify bank", "payout"],
    iconName: "bank",
  },
  {
    key: "payments-reports",
    type: "setting",
    title: "Payout reports",
    subtitle: "Statements, balance and refunds",
    route: `/brand/${BRAND_ID_TOKEN}/payments/reports`,
    group: "settings",
    minRank: 30,
    synonyms: [
      "payouts",
      "statements",
      "balance",
      "earnings",
      "reports",
      "refund",
      "refunds",
    ],
    iconName: "receipt",
  },
  {
    key: "pricing-defaults",
    type: "setting",
    title: "Pricing defaults",
    subtitle: "Fees, tax and currency",
    route: `/brand/${BRAND_ID_TOKEN}/pricing-defaults`,
    group: "settings",
    minRank: 50,
    synonyms: [
      "fees",
      "tax",
      "service fee",
      "pass fee",
      "absorb",
      "currency",
      "all-in",
    ],
    iconName: "pound",
  },
  {
    key: "tax-registrations",
    type: "setting",
    title: "Tax registrations",
    subtitle: "VAT, sales tax and tax IDs",
    // The embedded /connect-tax-registrations page needs a Stripe account
    // session token generated server-side (useBrandStripeTaxAccountSession);
    // visiting it directly shows "Invalid tax tools link". Route to the brand
    // payments hub, which launches the tax tools with a valid token.
    route: `/brand/${BRAND_ID_TOKEN}/payments`,
    group: "settings",
    minRank: 50,
    synonyms: ["vat", "sales tax", "tax settings", "tax id"],
    iconName: "receipt",
  },
  {
    key: "account-notifications",
    type: "setting",
    title: "Notifications",
    subtitle: "Push, email and reminders",
    route: "/account/notifications",
    group: "settings",
    minRank: 10,
    synonyms: ["push", "alerts", "email prefs", "reminders"],
    iconName: "bell",
  },
  {
    key: "account-edit",
    type: "setting",
    title: "Edit profile",
    subtitle: "Your name, avatar and photo",
    route: "/account/edit-profile",
    group: "settings",
    minRank: 10,
    synonyms: ["name", "avatar", "my profile", "photo"],
    iconName: "user",
  },
  {
    key: "account-delete",
    type: "action",
    title: "Delete account",
    subtitle: "Close your account for good",
    route: "/account/delete",
    group: "settings",
    minRank: 60,
    synonyms: ["close account", "remove account", "deactivate"],
    iconName: "trash",
  },
  {
    key: "create-event",
    type: "action",
    title: "Create event",
    subtitle: "Build a new event",
    route: "/event/create",
    group: "settings",
    minRank: 40,
    synonyms: ["new event", "add event", "build event"],
    iconName: "plus",
  },
  {
    key: "create-trip",
    type: "action",
    title: "Create trip",
    subtitle: "Plan a new trip",
    route: "/trip/create",
    group: "settings",
    minRank: 40,
    synonyms: ["new trip", "add trip", "plan trip"],
    iconName: "plus",
  },
  {
    key: "create-experience",
    type: "action",
    title: "Create experience",
    subtitle: "Add a new experience",
    route: "/experience/create",
    group: "settings",
    minRank: 40,
    synonyms: ["new experience", "add experience"],
    iconName: "plus",
  },
  {
    key: "connect-account-mgmt",
    type: "setting",
    title: "Manage payout account",
    subtitle: "Update bank in the Stripe dashboard",
    // The embedded /connect-account-management page needs a Stripe account
    // session token (shows "Invalid management link" without one). Route to
    // the brand payments hub, which launches it with a valid token.
    route: `/brand/${BRAND_ID_TOKEN}/payments`,
    group: "settings",
    minRank: 30,
    synonyms: ["stripe dashboard", "update bank", "manage account"],
    iconName: "bank",
  },
];
