import { useCallback, useEffect, useRef, useState } from "react";
import { AlertCard, SectionCard } from "../ui/Card";
import { checkAppReadiness, loadAppReadiness, parseEdgeError, recordAppReadinessEvent } from "../../services/adEngineService";
import { acceptRequest, analyticsPayload, demoteLatest, parseTargetQuery, refreshLatestFreshness, shouldRestoreCompletionFocus, targetKey, validateReadinessResponse, writeTargetQuery } from "../../lib/adAppReadiness";
import { TargetOverview } from "./TargetOverview";
import { TargetSelector } from "./TargetSelector";
import { SelectedTargetSummary } from "./SelectedTargetSummary";
import { ProviderReadinessList } from "./ProviderReadinessList";
import { FutureAppCampaignBoundary } from "./FutureAppCampaignBoundary";

const initialTarget = () => parseTargetQuery(window.location.search);
const emptyEntry = () => ({ phase: "loading_saved", latest: null, error: null, stopped: false, requestId: 0 });
const initialEntries = () => Object.fromEntries(["explorer","business"].flatMap((app) => ["ios","android"].map((os) => [targetKey(app,os), emptyEntry()])));

export function AppDownloadReadinessPanel() {
  const initial = initialTarget(); const [appKey,setAppKey]=useState(initial.appKey); const [os,setOs]=useState(initial.os);
  const [targets,setTargets]=useState([]); const [entries,setEntries]=useState(initialEntries); const [online,setOnline]=useState(navigator.onLine); const [announcement,setAnnouncement]=useState("");
  const selectedKey=targetKey(appKey,os); const entry=entries[selectedKey]; const selected=targets.find((target)=>targetKey(target.app_key,target.os)===selectedKey);
  const controllers=useRef({}); const requestIds=useRef(Object.fromEntries(Object.keys(entries).map((key)=>[key,0]))); const mounted=useRef(true); const actionRef=useRef(null); const viewed=useRef(false); const completionFocus=useRef(null); const serverOffsetMs=useRef(0);
  const emit=useCallback((eventName, extra={}) => { recordAppReadinessEvent(analyticsPayload(eventName,{appKey,os,...extra})).then(({error})=>{if(error) console.warn("[ad_app_readiness] analytics unavailable");}); },[appKey,os]);

  useEffect(()=>{ mounted.current=true; const activeControllers=controllers.current; return()=>{mounted.current=false; Object.values(activeControllers).forEach((controller)=>controller?.abort());};},[]);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine); window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
  useEffect(()=>{const refresh=()=>setEntries((current)=>Object.fromEntries(Object.entries(current).map(([key,value])=>[key,{...value,latest:refreshLatestFreshness(value.latest,Date.now()+serverOffsetMs.current)}])));const interval=window.setInterval(refresh,30000);const onVisibility=()=>{if(document.visibilityState==="visible")refresh();};window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",onVisibility);return()=>{window.clearInterval(interval);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",onVisibility);};},[]);
  useEffect(()=>{let active=true; const controller=new AbortController(); loadAppReadiness(appKey,os,{signal:controller.signal}).then(async({data,error})=>{if(!active||controller.signal.aborted)return; if(error){const parsed=await parseEdgeError(error);setEntries((current)=>({...current,[selectedKey]:{...current[selectedKey],phase:"error",error:{status:parsed?.status}}}));return;}const accepted=validateReadinessResponse(data,appKey,os);if(!accepted){setEntries((current)=>({...current,[selectedKey]:{...current[selectedKey],phase:"error",error:{status:500}}}));return;}serverOffsetMs.current=Date.parse(accepted.server_now)-Date.now();setTargets(accepted.targets);setEntries((current)=>Object.fromEntries(accepted.targets.map((target)=>{const key=targetKey(target.app_key,target.os);return[key,{...current[key],phase:"idle",latest:target.latest,error:null}];})));if(!viewed.current){viewed.current=true;emit("readiness_viewed",{freshnessBucket:accepted.selected.latest?"current":"none"});}});return()=>{active=false;controller.abort();}; // selected values are restored once on mount; checks own later refreshes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  useEffect(()=>{const pending=completionFocus.current;if(!pending)return;const action=actionRef.current;const restore=shouldRestoreCompletionFocus({pending,selectedKey,currentRequestId:requestIds.current[selectedKey],phase:entry.phase,online,buttonDisabled:!action||action.disabled});completionFocus.current=null;if(restore)action.focus();},[entry.phase,online,selectedKey]);

  const selectTarget=(nextApp,nextOs)=>{const outgoing=selectedKey;if(entries[outgoing].phase==="checking"){controllers.current[outgoing]?.abort();requestIds.current[outgoing]+=1;setEntries((current)=>({...current,[outgoing]:{...current[outgoing],phase:"idle",latest:demoteLatest(current[outgoing].latest),stopped:true}}));setAnnouncement(`${appKey} ${os} check stopped.`);}setAppKey(nextApp);setOs(nextOs);window.history.replaceState(null,"",writeTargetQuery(nextApp,nextOs));recordAppReadinessEvent(analyticsPayload("target_changed",{appKey:nextApp,os:nextOs}));};

  const runCheck=async()=>{if(!navigator.onLine){setOnline(false);return;}const capturedKey=selectedKey;const capturedApp=appKey;const capturedOs=os;controllers.current[capturedKey]?.abort();const controller=new AbortController();controllers.current[capturedKey]=controller;const requestId=++requestIds.current[capturedKey];const retry=entry.phase==="error"||entry.latest?.results?.some((row)=>row.verdict==="stale");setEntries((current)=>({...current,[capturedKey]:{...current[capturedKey],phase:"checking",latest:demoteLatest(current[capturedKey].latest),error:null,stopped:false,requestId}}));emit("check_started",{freshnessBucket:entry.latest?"stale":"none"});if(retry)emit("retry",{freshnessBucket:entry.latest?"stale":"none"});setAnnouncement(`${capturedApp} ${capturedOs} check started.`);const {data,error}=await checkAppReadiness(capturedApp,capturedOs,{signal:controller.signal});if(!acceptRequest({selectedKey:targetKey(appKey,os),capturedKey,currentRequestId:requestIds.current[capturedKey],capturedRequestId:requestId,mounted:mounted.current,aborted:controller.signal.aborted}))return;completionFocus.current={targetKey:capturedKey,requestId};if(error){const parsed=await parseEdgeError(error);setEntries((current)=>({...current,[capturedKey]:{...current[capturedKey],phase:"error",error:{status:parsed?.status}}}));setAnnouncement(`${capturedApp} ${capturedOs} check failed. No new result was accepted.`);return;}const accepted=validateReadinessResponse(data,capturedApp,capturedOs);if(!accepted){setEntries((current)=>({...current,[capturedKey]:{...current[capturedKey],phase:"error",error:{status:500}}}));return;}serverOffsetMs.current=Date.parse(accepted.server_now)-Date.now();setTargets(accepted.targets);setEntries((current)=>Object.fromEntries(accepted.targets.map((target)=>{const key=targetKey(target.app_key,target.os);return[key,{...current[key],phase:"idle",latest:target.latest,error:null,stopped:false,requestId:current[key].requestId}];})));emit("check_completed",{freshnessBucket:"current"});setAnnouncement(`${capturedApp} ${capturedOs}: check complete.`);};
  const errorStatus=entry?.error?.status; const alert=entry?.phase==="error"?(errorStatus===401?"Your admin session expired. Sign in again to continue.":errorStatus===403?"Admin permission is required to run this check.":errorStatus===408?"The check timed out. No new result was accepted.":"The readiness response could not be accepted. Prior evidence is not current."):!online?"You’re offline. Reconnect, then retry.":null;
  const providerEvent=(eventName,result)=>emit(eventName,{provider:result.provider,verdict:result.verdict,reasonCode:result.reason_code,freshnessBucket:result.verdict==="stale"?"stale":"current"});
  return <SectionCard title="App-download readiness" className="@container"><div className="space-y-6" aria-busy={entry?.phase==="loading_saved"||entry?.phase==="checking"}>
    <p className="max-w-[72ch] text-sm leading-5 text-[var(--color-text-secondary)]">Check whether Mingla’s corporate ad accounts, public identities, exact app binding, measurement, funding, and permissions are ready for this app and platform. Nothing is created or spent here.</p>
    <TargetOverview targets={targets} selectedKey={selectedKey} loading={!targets.length}/><TargetSelector appKey={appKey} os={os} onChange={selectTarget}/>
    {alert&&<AlertCard variant={online?"error":"warning"} title={online?"Check unavailable":"Offline"}><span role="alert">{alert}</span></AlertCard>}
    {selected&&<><SelectedTargetSummary target={{...selected,latest:entry.latest}} phase={entry.phase} stopped={entry.stopped} onCheck={errorStatus===401?()=>{window.location.href="/login";}:errorStatus===403?()=>{window.location.href="/";}:runCheck} actionRef={actionRef} offline={!online} errorStatus={errorStatus}/><ProviderReadinessList latest={entry.latest} onEvent={providerEvent}/></>}
    <FutureAppCampaignBoundary/><div role="status" aria-live="polite" aria-atomic="true" className="sr-only">{announcement}</div>
  </div></SectionCard>;
}
