/**
 * #1559 [shared-venue-screen] — RENDER-PARITY PROOF for a pure move.
 *
 * Step 3 of #1550 moves the entire public venue body out of
 * `mingla-business/src/components/venue/PublicVenuePage.tsx` and into
 * `packages/brand-rendering/PublicVenueScreen.tsx`. The acceptance criterion is
 * NOT "it still renders" — it is that it renders **the same**.
 *
 * HOW THIS PROVES IT, and why it is not circular:
 *
 *   1. The baseline JSON in `__fixtures__/publicVenueRenderParity.issue1559.
 *      baseline.json` was generated by running THIS file's harness against the
 *      PRE-MOVE tree (commit `bc852b2c8`, `MINGLA_1559_WRITE_BASELINE=1`), when
 *      the route still mounted `<PublicVenuePage>`. It is a recorded artefact of
 *      the old implementation, committed unchanged.
 *   2. The harness mounts the REAL route component
 *      (`app/b/[brandSlug]/v/[venueSlug].tsx`) — the adapter itself, not a
 *      hand-rebuilt copy of it — with the data hooks and the app-owned
 *      host slots stubbed. Everything between the route and the pixels runs for
 *      real: theme resolution, the category profile, the section registry, the
 *      tab reducer, the reserve gate, the desktop panel, the StyleSheet values.
 *   3. Post-move the same harness must reproduce the baseline EXACTLY. Any
 *      changed element, prop, style value, order or copy string fails.
 *
 * VACUITY GUARDS (this PR exists because a gate went vacuously green — the same
 * mistake must not be made here):
 *   - the baseline must exist and parse (readFileSync throws otherwise);
 *   - it must carry exactly the CASES declared below, by name;
 *   - every case's serialised tree must exceed a minimum size, so an
 *     accidentally-null render can never "match";
 *   - every case must contain its declared ANCHORS, so a tree that rendered but
 *     lost the venue body cannot pass;
 *   - `expect.assertions` pins the count per case.
 *
 * APPEND-ONLY — new file; modifies/deletes no existing test.
 *
 * ---------------------------------------------------------------------------
 * [TEST-MOD-APPROVED #1561] — WHAT THIS FILE MEANS AFTER #1561
 * ---------------------------------------------------------------------------
 * #1559's question was "did the MOVE change anything?" and the answer was no.
 * #1561 is the step that changes it ON PURPOSE: the gallery becomes the hero,
 * the answer bar appears, the hero is capped, the bottom `PHOTOS` strip is
 * deleted and the `VERIFIED VENUE` eyebrow is replaced by the category chip.
 * A baseline recorded from the PRE-MOVE tree therefore cannot keep passing —
 * and it should not, because a redesign that left that tree intact would be a
 * redesign that did nothing.
 *
 * So the baseline was REGENERATED against #1561's tree
 * (`MINGLA_1561_WRITE_BASELINE=1 npx jest publicVenueRenderParity.issue1559`),
 * and the anchors below were updated to name the things the first screen
 * carries NOW. Everything that made this file worth having is untouched:
 * the same seven cases, the same size floor, the same anchor guard, the same
 * `expect.assertions` pin. Its job changes from "prove the move was clean" to
 * "prove the redesigned page does not drift"; the deleted anchors (`VERIFIED
 * VENUE`, `PHOTOS`) are replaced by anchors for the blocks that took their
 * place, so the guard never gets weaker, only re-aimed.
 *
 * Lines were DELETED (anchor strings, the baseline JSON), which is why the
 * token above is required and why it is stated here rather than only in the
 * commit body.
 *
 * ---------------------------------------------------------------------------
 * [TEST-MOD-APPROVED #1564] — WHAT THIS FILE MEANS AFTER #1564
 * ---------------------------------------------------------------------------
 * #1564 hands the resolved palette to the table-reservation booking body, which
 * had been painting itself Mingla orange (`#eb7825`) and near-black
 * (`#0c0e12`) regardless of the page behind it — while the Stay body beside it
 * had received the palette all along. The `GuestVenueReservationStub` below
 * echoes its props, so the baseline necessarily gains a `palette` object on the
 * three RESTAURANT cases. That is the fix arriving, not drift.
 *
 * The regenerated baseline (`MINGLA_1559_WRITE_BASELINE=1 npx jest
 * publicVenueRenderParity.issue1559`) is a diff of **+48 lines, -0**: 16 lines
 * of palette on each of `restaurant-phone-full`, `restaurant-desktop-full` and
 * `restaurant-phone-menu-tab`, and NOTHING removed. The four Stay cases are
 * byte-identical. No case, anchor, size floor or `expect.assertions` pin
 * changed — this file's guard is not re-aimed here, only re-recorded.
 *
 * ---------------------------------------------------------------------------
 * [TEST-MOD-APPROVED #1615] — WHAT THIS FILE MEANS AFTER #1615
 * ---------------------------------------------------------------------------
 * #1615 deliberately adds the measured Direction C identity overlay and the
 * venue-specific canonical OG image to the buyer-web venue page. The previous
 * baseline therefore described the old UI rather than a valid invariant. It is
 * regenerated with the same seven cases, size floor, anchors, and exact-tree
 * comparison; only the approved overlay and metadata URL change.
 *
 * ---------------------------------------------------------------------------
 * [TEST-MOD-APPROVED #2508] — WHAT THIS FILE MEANS AFTER #2508
 * ---------------------------------------------------------------------------
 * #2508 [maps-app-chooser] deliberately adds TWO controls to the venue card:
 * a "Copy address" button beside it, and a chooser that asks Apple Maps or
 * Google Maps instead of silently picking one. A baseline that kept passing
 * would mean the feature did not arrive.
 *
 * Regenerated with `MINGLA_1559_WRITE_BASELINE=1 npx jest
 * publicVenueRenderParity.issue1559`. The decoded diff is **+1215 lines, -0**,
 * evenly +243 on each of the five cases that render an address card
 * (restaurant-phone-full, restaurant-desktop-full, stay-phone-full,
 * play-phone-reservability-error, uncategorised-phone-sparse); the two cases
 * that render no address card (stay-desktop-reservations-tab,
 * restaurant-phone-menu-tab) are BYTE-IDENTICAL, which is itself the proof
 * that nothing outside the venue card moved.
 *
 * NOTHING WAS REMOVED — no case, no anchor, no size floor, no
 * `expect.assertions` pin, and no pre-existing subtree. The only new content is
 * the copy button (`issue-2508-copy-address`) and the chooser
 * (`issue-2508-maps-app-chooser` with its apple / google / cancel rows). This
 * file's guard is re-recorded here, never re-aimed or weakened.
 *
 * PRIVACY NOTE: the venue page has no hide-address concept, so all five
 * address-card cases legitimately gain both controls. The hidden-address
 * behaviour — a withheld street exposing NEITHER control — lives on the
 * event/RSVP pages and is pinned by
 * packages/offering-rendering/__tests__/issue_2508_maps_app_chooser.test.ts T-6.
 */
import React from "react";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, expect, jest, test } from "@jest/globals";

import type { VenueCategory } from "@mingla/brand-rendering/venueCategoryProfile";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT =
  true;

// `src/constants/platformUrl.ts` throws at module load without this — the same
// production canonical every other suite pins (publicUrls.test.ts et al).
process.env.EXPO_PUBLIC_MINGLA_BUSINESS_WEB_URL = "https://host.usemingla.com";

// ---------------------------------------------------------------------------
// Harness plumbing
// ---------------------------------------------------------------------------

const BASELINE_PATH = join(
  __dirname,
  "__fixtures__",
  "publicVenueRenderParity.issue1559.baseline.json",
);
const WRITE_BASELINE = process.env.MINGLA_1559_WRITE_BASELINE === "1" ||
  process.env.MINGLA_1561_WRITE_BASELINE === "1";

/** Viewport the mocked `useResponsiveLayout` reports for the current case. */
const viewport: { isDesktop: boolean; width: number } = {
  isDesktop: false,
  width: 390,
};

/** Data the mocked query hooks hand the route for the current case. */
interface CaseData {
  venue: Record<string, unknown> | null;
  menu: unknown[];
  reservable: Record<string, unknown> | null;
  reservableState: "loading" | "ready" | "error";
  discoveryPrice: Record<string, unknown> | null;
  stayDetail: Record<string, unknown> | null;
  stayState: "loading" | "ready" | "unavailable" | "error";
  tab: string | undefined;
}
const caseData: { current: CaseData } = {
  current: {
    venue: null,
    menu: [],
    reservable: null,
    reservableState: "ready",
    discoveryPrice: null,
    stayDetail: null,
    stayState: "ready",
    tab: undefined,
  },
};

// ---- module mocks: everything OUTSIDE the moved code ----------------------

jest.mock("expo-router", () => ({
  __esModule: true,
  useLocalSearchParams: () => ({
    brandSlug: "smokerhythm",
    venueSlug: "academy-street-bistro",
    tab: caseData.current.tab,
  }),
  useRouter: () => ({
    push: () => undefined,
    replace: () => undefined,
    back: () => undefined,
    canGoBack: () => true,
  }),
}));

// `Head` must stay INERT but present in the tree at the position it occupies,
// so a moved <Head> would show up as a diff rather than silently vanish.
jest.mock("expo-router/head", () => {
  const ReactLocal = require("react") as typeof React;
  const Head = (props: { children?: React.ReactNode }): React.ReactElement =>
    ReactLocal.createElement("ExpoHead", null, props.children);
  return { __esModule: true, default: Head };
});

jest.mock("react-native-safe-area-context", () => ({
  __esModule: true,
  useSafeAreaInsets: () => ({ top: 47, bottom: 34, left: 0, right: 0 }),
}));

// The offering-rendering barrel: REAL pure helpers (theme, palette, surface,
// static map) so every colour and style value below is genuinely computed; the
// shell becomes a transparent passthrough so the body it wraps is observable.
// [TEST-MOD-APPROVED #2508] Harness registration only — ADDITION, no assertion
// changed. The shared copy-address button and map-app chooser draw lucide
// glyphs through `react-native-svg` (a REAL dependency of both apps —
// react-native-svg 15.12.1 — and an existing peer of @mingla/offering-rendering).
// This render config simply cannot resolve it from `packages/`, so it is mocked
// to plain react-native Views, the same idiom
// issue_1890_ari_composer_clearance uses. Nothing this suite asserts is a glyph.
jest.mock(
  "react-native-svg",
  () => {
    const Glyph = (): null => null;
    return {
      __esModule: true,
      default: Glyph,
      Svg: Glyph,
      Path: Glyph,
      Circle: Glyph,
      Rect: Glyph,
      G: Glyph,
      Defs: Glyph,
      Stop: Glyph,
      LinearGradient: Glyph,
    };
  },
  { virtual: true },
);

jest.mock("@mingla/offering-rendering", () => {
  const ReactLocal = require("react") as typeof React;
  const themeResolver = require("../../../../../packages/offering-rendering/themeResolver");
  const themePalette = require("../../../../../packages/offering-rendering/themePalette");
  const mapboxStaticImage = require("../../../../../packages/offering-rendering/mapboxStaticImage");
  // [TEST-MOD-APPROVED #2468] Harness registration only — ADDITION, no
  // assertion changed. maps-deep-link-coordinates gave every "open in maps"
  // URL one owner (packages/offering-rendering/mapsDeepLink), and the shared
  // venue screen now reads its maps target from it. Registering the REAL module
  // matches this factory's rule of spreading the real pure helpers.
  const mapsDeepLink = require("../../../../../packages/offering-rendering/mapsDeepLink");
  // [TEST-MOD-APPROVED #2508] Harness registration only — ADDITION, no
  // assertion changed. maps-app-chooser added the shared "which map app?"
  // chooser + copy-address button, and PublicVenueScreen reaches them through
  // THIS barrel (its only barrel-sourced UI). Registering the REAL module
  // matches this factory's rule of spreading the real helpers, and keeps the
  // venue card's rendered output genuine rather than stubbed away.
  const venueMapsActions = require("../../../../../packages/offering-rendering/VenueMapsActions");
  const ParallaxCoverShell = (
    props: Record<string, unknown>,
  ): React.ReactElement => {
    const { children, heroEyebrow, heroTitle, stickyPanel, ...rest } = props as {
      children?: React.ReactNode;
      heroEyebrow?: React.ReactNode;
      heroTitle?: React.ReactNode;
      stickyPanel?: React.ReactNode;
    };
    return ReactLocal.createElement(
      "ParallaxCoverShell",
      // Function props are dropped by the serialiser; the scalar props are the
      // shell contract and MUST stay identical across the move.
      rest,
      ReactLocal.createElement("ShellHeroEyebrow", null, heroEyebrow),
      ReactLocal.createElement("ShellHeroTitle", null, heroTitle),
      ReactLocal.createElement("ShellStickyPanel", null, stickyPanel),
      ReactLocal.createElement("ShellBody", null, children),
    );
  };
  return {
    __esModule: true,
    ...themeResolver,
    ...themePalette,
    ...mapboxStaticImage,
    ...mapsDeepLink,
    ...venueMapsActions,
    useResponsiveLayout: () => ({
      width: viewport.width,
      isDesktop: viewport.isDesktop,
      isPhone: !viewport.isDesktop,
      isWeb: true,
    }),
    ParallaxCoverShell,
  };
});

jest.mock("../../../theme/useThemeFont", () => ({
  __esModule: true,
  useThemeFont: (family: string | null | undefined) => {
    themeFontRequests.push(family ?? null);
    return { loaded: true };
  },
  loadThemeFont: async () => undefined,
}));
const themeFontRequests: (string | null)[] = [];

jest.mock("../../../analytics/webAnalytics", () => ({
  __esModule: true,
  captureWeb: (event: string, props: Record<string, unknown>) => {
    analyticsCalls.push({ event, props });
  },
  captureAdClickIds: () => undefined,
}));
const analyticsCalls: { event: string; props: Record<string, unknown> }[] = [];

jest.mock("../../../services/venueOrganicCaptureService", () => ({
  __esModule: true,
  captureVenueOrganicEvent: async () => undefined,
  settleVenueOrganicJourneyOnConsent: () => () => undefined,
}));

// App-owned host slots — unchanged by this move, stubbed so their PROPS (which
// must stay identical) land in the serialised tree.
jest.mock("../../ui/ShareModal", () => {
  const ReactLocal = require("react") as typeof React;
  return {
    __esModule: true,
    // [TEST-MOD-APPROVED #1719] `contentKind` is a new invisible discriminator
    // for the unified share adapter. #1719 tests that behavior directly; omit
    // it from this legacy visual-tree oracle so the public venue pixels remain
    // the parity surface measured here.
    ShareModal: ({ contentKind: _contentKind, ...props }: Record<string, unknown>) =>
      ReactLocal.createElement("ShareModalStub", props),
  };
});
jest.mock("../GuestVenueReservation", () => {
  const ReactLocal = require("react") as typeof React;
  return {
    __esModule: true,
    GuestVenueReservation: (props: Record<string, unknown>) =>
      ReactLocal.createElement("GuestVenueReservationStub", props),
  };
});
jest.mock("../PublicVenueReservationSheet", () => {
  const ReactLocal = require("react") as typeof React;
  return {
    __esModule: true,
    PublicVenueReservationSheet: (props: Record<string, unknown>) => {
      const { children, ...rest } = props as { children?: React.ReactNode };
      return ReactLocal.createElement(
        "PublicVenueReservationSheetStub",
        rest,
        children,
      );
    },
  };
});
jest.mock("../PublicVenueNotFound", () => {
  const ReactLocal = require("react") as typeof React;
  return {
    __esModule: true,
    PublicVenueNotFound: (props: Record<string, unknown>) =>
      ReactLocal.createElement("PublicVenueNotFoundStub", props),
  };
});
jest.mock("../../stay/BuyerStayGuestExperience", () => {
  const ReactLocal = require("react") as typeof React;
  return {
    __esModule: true,
    BuyerStayGuestExperience: (props: Record<string, unknown>) =>
      ReactLocal.createElement("BuyerStayGuestExperienceStub", props),
  };
});

jest.mock("../../../hooks/usePublicEvents", () => ({
  __esModule: true,
  usePublicVenueBySlug: () => ({
    data: caseData.current.venue,
    isLoading: false,
    isFetching: false,
    isError: false,
  }),
  usePublicVenueReservable: () => ({
    data: caseData.current.reservable,
    isLoading: caseData.current.reservableState === "loading",
    isError: caseData.current.reservableState === "error",
    refetch: () => undefined,
  }),
  usePublicVenueDiscoveryPrice: () => ({
    data: caseData.current.discoveryPrice,
  }),
  usePublicBrandBySlug: () => ({ data: null }),
}));
jest.mock("../../../hooks/useMenus", () => ({
  __esModule: true,
  usePublicMenus: () => ({ data: caseData.current.menu }),
}));
jest.mock("../../../hooks/usePublicStayDetail", () => ({
  __esModule: true,
  usePublicStayDetail: () => ({
    data: caseData.current.stayDetail,
    isLoading: caseData.current.stayState === "loading",
    isError: caseData.current.stayState === "error",
  }),
}));

// ---------------------------------------------------------------------------
// Fixtures — real-shaped data, not placeholders
// ---------------------------------------------------------------------------

const HOURS = [
  { weekday: 0, openTime: "09:00", closeTime: "17:00", isClosed: false },
  { weekday: 1, openTime: "09:00", closeTime: "17:00", isClosed: false },
  { weekday: 2, openTime: "09:00", closeTime: "22:30", isClosed: false },
  { weekday: 3, openTime: "09:00", closeTime: "22:30", isClosed: false },
  { weekday: 4, openTime: "10:00", closeTime: "23:00", isClosed: false },
  { weekday: 5, openTime: "10:00", closeTime: "23:00", isClosed: false },
  { weekday: 6, openTime: null, closeTime: null, isClosed: true },
];

const baseVenue = (
  venueCategory: VenueCategory | null,
): Record<string, unknown> => ({
  id: "11111111-1111-4111-8111-111111111111",
  brandId: "22222222-2222-4222-8222-222222222222",
  brandSlug: "smokerhythm",
  brandName: "Smoke & Rhythm",
  slug: "academy-street-bistro",
  name: "Academy Street Bistro",
  address: "12 Academy Street, London N1 4AB",
  city: "London",
  countryCode: "GB",
  lat: 51.5361,
  lng: -0.1035,
  venueCategory,
  contactEmail: "hello@example.com",
  contactPhone: "+442071234567",
  coverMediaUrl: "https://cdn.example.com/cover.jpg",
  coverMediaType: "image",
  placePoolId: "33333333-3333-4333-8333-333333333333",
  theme: { color: "#eb7825", font: "inter", animation: null },
  coverHue: 24,
  defaultCurrency: "GBP",
  hours: HOURS,
  galleryPhotoUrls: [
    "https://cdn.example.com/g1.jpg",
    "https://cdn.example.com/g2.jpg",
    "https://cdn.example.com/g3.jpg",
  ],
  pitch:
    "A neighbourhood bistro with an open fire, a short menu that changes weekly, and a wine list built entirely from small growers. Walk-ins welcome at the bar; the dining room books up quickly at weekends, so reserve ahead if you want the corner table.",
});

const MENU = [
  {
    menuId: "menu-1",
    menuName: "Small plates",
    menuDescription: "To share, or not",
    items: [
      {
        id: "item-1",
        name: "Devilled eggs",
        description: "Smoked paprika",
        priceCents: 650,
        currency: "GBP",
      },
      {
        id: "item-2",
        name: "Bread & cultured butter",
        description: null,
        priceCents: null,
        currency: "GBP",
      },
    ],
  },
];

const STAY_DETAIL = {
  venueId: "11111111-1111-4111-8111-111111111111",
  checkInTime: "15:00:00",
  checkOutTime: "11:00",
  houseRules: "No parties. Quiet hours after 22:00.",
  rooms: [],
  places: [],
  placeWindows: [],
};

const RESERVABLE = {
  reservable: true,
  venueId: "11111111-1111-4111-8111-111111111111",
  currency: "GBP",
};

const DISCOVERY_PRICE = {
  minMinor: 2500,
  maxMinor: 6000,
  currencyCode: "GBP",
  minorUnitExponent: 2,
};

interface ParityCase {
  name: string;
  data: CaseData;
  desktop: boolean;
  /** Substrings that MUST appear in the serialised tree (vacuity guard). */
  anchors: string[];
  /** Optional tab to press after mount, so a non-default pane is captured. */
  pressTab?: "Overview" | "Menu" | "Reservations";
}

const CASES: ParityCase[] = [
  {
    name: "restaurant-phone-full",
    desktop: false,
    anchors: [
      // #1561 — the category chip replaces the VERIFIED VENUE eyebrow, and the
      // answer bar replaces the bottom PHOTOS strip as this case's proof that
      // the first screen rendered.
      "Restaurant",
      "London",
      "Typically",
      "Booking",
      "Academy Street Bistro",
      "WHERE YOU'LL BE",
      "HOURS",
      "Reserve a table",
      "Typical spend",
      "Read more",
    ],
    data: {
      venue: baseVenue("restaurant"),
      menu: MENU,
      reservable: RESERVABLE,
      reservableState: "ready",
      discoveryPrice: DISCOVERY_PRICE,
      stayDetail: null,
      stayState: "ready",
      tab: undefined,
    },
  },
  {
    name: "restaurant-desktop-full",
    desktop: true,
    anchors: [
      "Academy Street Bistro",
      "WHERE YOU'LL BE",
      "HOURS",
      "Reserve a table",
      "Share",
      // [TEST-MOD-APPROVED #1562] — this list HELD "Open today", and #1562
      // deleted that string from the product.
      //
      // It was a literal open-now CLAIM derived from a WEEKDAY MATCH: it never
      // compared the current clock to the venue's open or close time, and it
      // read the VISITOR's device weekday, so #1550 Leg C photographed it
      // asserting a Miami restaurant was open at 03:00. An anchor that pins a
      // false claim in place is worse than no anchor.
      //
      // It is REMOVED rather than replaced because this fixture publishes no
      // `timezone` (the field is new here), so the panel resolves `unknown` and
      // deliberately states NOTHING — see `venueOpenStateLine`'s docblock for
      // why a device-weekday degrade was rejected. The replacement is pinned
      // far harder elsewhere: `venueOpenState.issue1562.happy.test.ts` fakes
      // the clock and asserts every one of open / opens-later / closed /
      // unknown, the boundary minute at both ends, an overnight span and a
      // non-machine timezone, and `venueFirstScreen.issue1562.happy.test.tsx`
      // reads the resulting strings off the REAL rendered tree at five widths.
      // One substring match traded for that is a strengthening.
    ],
    data: {
      venue: baseVenue("restaurant"),
      menu: MENU,
      reservable: RESERVABLE,
      reservableState: "ready",
      discoveryPrice: DISCOVERY_PRICE,
      stayDetail: null,
      stayState: "ready",
      tab: undefined,
    },
  },
  {
    name: "stay-phone-full",
    desktop: false,
    anchors: [
      // #1561 — "Hotel" is the category chip; "Check-in" is the answer bar's
      // time cell, which on a Stay is what a guest is actually asking.
      "Hotel",
      "Check-in",
      "CHECK-IN",
      "Reserve this Stay",
      "15:00",
      "11:00",
    ],
    data: {
      venue: baseVenue("stay"),
      menu: [],
      reservable: null,
      reservableState: "ready",
      discoveryPrice: null,
      stayDetail: STAY_DETAIL,
      stayState: "ready",
      tab: undefined,
    },
  },
  {
    name: "stay-desktop-reservations-tab",
    desktop: true,
    // `?tab=reservations` lands on the Reservations pane, so the Overview
    // sections are deliberately NOT mounted here — the anchors pin the booking
    // surface instead. (A stray "CHECK-IN" in this tree would mean the tab
    // reducer stopped honouring the deep link.)
    anchors: [
      "Academy Street Bistro",
      "Reserve this Stay",
      // The Stay booking body is behind a React.lazy boundary that does not
      // resolve synchronously, so the Suspense fallback is what a first paint
      // shows — and that fallback is itself part of the moved surface.
      "Loading Stay availability",
    ],
    data: {
      venue: baseVenue("stay"),
      menu: [],
      reservable: null,
      reservableState: "ready",
      discoveryPrice: null,
      stayDetail: STAY_DETAIL,
      stayState: "ready",
      tab: "reservations",
    },
  },
  {
    name: "play-phone-reservability-error",
    desktop: false,
    anchors: ["Book a visit", "HOURS", "WHERE YOU'LL BE"],
    data: {
      venue: baseVenue("play"),
      menu: [],
      reservable: null,
      reservableState: "error",
      discoveryPrice: null,
      stayDetail: null,
      stayState: "ready",
      tab: undefined,
    },
  },
  {
    name: "restaurant-phone-menu-tab",
    desktop: false,
    // Presses the Menu pill so the shared PublicMenuSections pane — one of the
    // pieces this PR moves — is actually in the captured tree.
    pressTab: "Menu",
    anchors: ["MENU", "Small plates", "Devilled eggs", "£6.50"],
    data: {
      venue: baseVenue("restaurant"),
      menu: MENU,
      reservable: RESERVABLE,
      reservableState: "ready",
      discoveryPrice: DISCOVERY_PRICE,
      stayDetail: null,
      stayState: "ready",
      tab: undefined,
    },
  },
  {
    name: "uncategorised-phone-sparse",
    desktop: false,
    // A venue with almost no data: proves the omit-when-absent arms are
    // identical too, not just the fully-populated happy path.
    // #1561 — the ZERO-DATA case. No cover, no photographs, no address, no
    // city, no hours, no pitch: the category chip is the ONLY chip (there is no
    // place to name), and the hero placeholder must read "Venue", never the
    // literal word `COVER` that #1550 Leg C photographed on a live public page.
    anchors: ["Venue", "Academy Street Bistro", "By"],
    data: {
      venue: {
        ...baseVenue(null),
        address: null,
        city: null,
        pitch: null,
        hours: [],
        galleryPhotoUrls: [],
        coverMediaUrl: null,
        coverMediaType: null,
        theme: null,
      },
      menu: [],
      reservable: null,
      reservableState: "ready",
      discoveryPrice: null,
      stayDetail: null,
      stayState: "ready",
      tab: undefined,
    },
  },
];

// ---------------------------------------------------------------------------
// Serialisation — stable, function-free, order-preserving
// ---------------------------------------------------------------------------

interface TestInstance {
  type: unknown;
  props: Record<string, unknown>;
  findAll: (predicate: (node: TestInstance) => boolean) => TestInstance[];
}

interface MountedTree {
  toJSON: () => unknown;
  unmount: () => void;
  root: TestInstance;
}

const TestRenderer = require("react-test-renderer") as {
  create: (
    element: React.ReactElement,
    options?: { createNodeMock?: () => object },
  ) => MountedTree;
  act: (callback: () => void) => void;
};

/**
 * `toJSON()` already drops functions and refs. This normaliser additionally
 * sorts object keys so a purely cosmetic prop-order change is not reported as a
 * behavioural diff, and leaves ARRAY order (children, style arrays) untouched
 * because array order IS layout.
 */
const stable = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(stable);
  if (value !== null && typeof value === "object") {
    const source = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(source).sort()) {
      if (typeof source[key] === "function") continue;
      out[key] = stable(source[key]);
    }
    return out;
  }
  return value;
};

const renderCase = (parityCase: ParityCase): string => {
  viewport.isDesktop = parityCase.desktop;
  viewport.width = parityCase.desktop ? 1440 : 390;
  caseData.current = parityCase.data;
  // Required so the "today" row highlight is deterministic across runs.
  jest.useFakeTimers().setSystemTime(new Date("2026-08-05T12:00:00.000Z"));
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const routeModule = require("../../../../app/b/[brandSlug]/v/[venueSlug]");
  const Route = (routeModule.default ?? routeModule) as React.ComponentType;
  let renderer: MountedTree | null = null;
  TestRenderer.act(() => {
    renderer = TestRenderer.create(React.createElement(Route));
  });
  if (renderer === null) throw new Error("route did not mount");
  const mounted: MountedTree = renderer;
  // Flush the mount effects (the tab reducer's INITIAL_TAB_CHANGED /
  // ENVIRONMENT_CHANGED dispatches) so the tree is the settled one a guest sees.
  TestRenderer.act(() => undefined);
  if (parityCase.pressTab !== undefined) {
    const label = parityCase.pressTab;
    const tab = mounted.root.findAll(
      (node) =>
        node.props.accessibilityRole === "tab" &&
        node.props.accessibilityLabel === label,
    )[0];
    if (tab === undefined) {
      throw new Error(`no "${label}" tab to press — the tab strip regressed`);
    }
    const onPress = tab.props.onPress;
    if (typeof onPress !== "function") {
      throw new Error(`the "${label}" tab has no onPress — dead tap`);
    }
    TestRenderer.act(() => {
      (onPress as () => void)();
    });
  }
  const tree: unknown = mounted.toJSON();
  mounted.unmount();
  jest.useRealTimers();
  return JSON.stringify(stable(tree), null, 1);
};

// ---------------------------------------------------------------------------
// The proof
// ---------------------------------------------------------------------------

describe("#1559 public venue render parity — the move changes nothing a guest sees", () => {
  const rendered = new Map<string, string>();
  for (const parityCase of CASES) {
    rendered.set(parityCase.name, renderCase(parityCase));
  }

  if (WRITE_BASELINE) {
    mkdirSync(dirname(BASELINE_PATH), { recursive: true });
    writeFileSync(
      BASELINE_PATH,
      `${JSON.stringify(Object.fromEntries(rendered), null, 1)}\n`,
      "utf8",
    );
  }

  // ---- vacuity guards ----------------------------------------------------

  test("the baseline artefact exists and covers exactly the declared cases", () => {
    expect(existsSync(BASELINE_PATH)).toBe(true);
    const baseline = JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as Record<
      string,
      string
    >;
    expect(Object.keys(baseline).sort()).toEqual(
      CASES.map((c) => c.name).sort(),
    );
    expect(CASES).toHaveLength(7);
  });

  test("every rendered tree is substantial — a null render cannot 'match'", () => {
    expect.assertions(CASES.length * 2);
    for (const parityCase of CASES) {
      const tree = rendered.get(parityCase.name) ?? "";
      expect(tree.length).toBeGreaterThan(4000);
      expect(tree).toContain('"type"');
    }
  });

  test("every rendered tree still carries the venue body it is supposed to", () => {
    const anchorCount = CASES.reduce((n, c) => n + c.anchors.length, 0);
    expect.assertions(anchorCount);
    for (const parityCase of CASES) {
      const tree = rendered.get(parityCase.name) ?? "";
      for (const anchor of parityCase.anchors) {
        // JSON-escape so an apostrophe in "WHERE YOU'LL BE" still matches.
        const needle = JSON.stringify(anchor).slice(1, -1);
        expect(tree.includes(needle) ? anchor : `MISSING:${anchor}`).toBe(
          anchor,
        );
      }
    }
  });

  // ---- the parity assertion itself ---------------------------------------

  test.each(CASES.map((c) => c.name))(
    "%s renders byte-identically to the pre-move baseline",
    (name) => {
      const baseline = JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as Record<
        string,
        string
      >;
      const before = baseline[name];
      const after = rendered.get(name);
      expect(typeof before).toBe("string");
      expect(after).toBe(before);
    },
  );

  test("the brand theme font is requested on every mount", () => {
    // The move turns `useThemeFont(...)` into an injected host capability; if
    // the injection is dropped, a themed venue silently loses its brand font
    // and every parity tree above would still match (fontFamily comes from the
    // resolved theme, not from the loader). This is the one behaviour the tree
    // diff cannot see, so it is asserted directly.
    expect(themeFontRequests.length).toBeGreaterThanOrEqual(CASES.length);
    expect(themeFontRequests).toContain("Inter_500Medium");
  });
});
