import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { accent, canvas, spacing, text, typography } from "../../constants/designSystem";
import { useAuth } from "../../context/AuthContext";
import { useAudienceList } from "../../hooks/marketing/useAudienceList";
import { useBrandPeople } from "../../hooks/marketing/useBrandPeople";
import { useCurrentBrand } from "../../hooks/useCurrentBrand";
import { useCurrentBrandRole } from "../../hooks/useCurrentBrandRole";
import { useFeatureFlag } from "../../hooks/useFeatureFlag";
import { useResponsiveLayout } from "../../hooks/useResponsiveLayout";
import { ensureBrandBuyersAudience, ensureEventBuyersAudience } from "../../services/marketing/marketingCampaignService";
import type { AudienceListEntry } from "../../types/marketing";
import type { AddBrandPersonResult, BrandPersonSummary } from "../../types/people";
import { useShareNetworkState } from "../ui/useShareNetworkState";
import { Button } from "../ui/Button"; import { EmptyState } from "../ui/EmptyState"; import { Skeleton } from "../ui/Skeleton"; import { Toast } from "../ui/Toast";
import { AudienceCard } from "../marketing/AudienceCard";
import { capturePeople } from "../../features/people/peopleAnalytics";
import { AddPersonSheet } from "./AddPersonSheet";
import { BookSheet, DependencyStatus, GroupsSheet, PeopleBlock, PeopleRow } from "./PeoplePrimitives";

const contacts=(n:number|null):string|undefined=>n===null?undefined:`${n} ${n===1?"contact":"contacts"}`;
export function PeoplePage():React.ReactElement{
  const router=useRouter(),brand=useCurrentBrand(),role=useCurrentBrandRole(brand?.id??null),{isAuthReady,user}=useAuth(),online=useShareNetworkState();
  const {isWideDesktop,width}=useResponsiveLayout(); const actionColumns=width>0&&width<352?1:isWideDesktop?4:2; const actionCell={flexBasis:actionColumns===1?"100%":actionColumns===2?"48%":0,flexGrow:1,minWidth:0} as const;
  const roleResolved=!role.isLoading&&!role.isError; const authorized=isAuthReady&&user!==null&&roleResolved&&role.accepted&&role.rank>=20;
  const book=useBrandPeople(brand?.id??null,null,roleResolved&&role.accepted,role.rank,online); const [bookSearch,setBookSearch]=React.useState(""); const sheetBook=useBrandPeople(brand?.id??null,bookSearch||null,roleResolved&&role.accepted,role.rank,online); const groups=useAudienceList(user?.id??null); const flag=useFeatureFlag("contact_import_v1");
  const importEnabled=authorized&&online&&!flag.isPending&&!flag.isFetching&&!flag.isError&&flag.data===true;
  const [bookOpen,setBookOpen]=React.useState(false),[groupsOpen,setGroupsOpen]=React.useState(false),[addOpen,setAddOpen]=React.useState(false),[creatingKey,setCreatingKey]=React.useState<string|null>(null),[toast,setToast]=React.useState<{message:string;kind:"success"|"error"}|null>(null);
  React.useEffect(()=>{capturePeople("people_page_viewed",{surface:"page"})},[]); React.useEffect(()=>{setBookOpen(false);setGroupsOpen(false);setAddOpen(false)},[brand?.id]);
  React.useEffect(()=>{if(!flag.isPending&&!flag.isFetching){capturePeople("people_dependency_state_viewed",{surface:"page",dependency:"import",dependencyState:flag.isError||flag.data!==true?"unavailable":"available"})}},[flag.data,flag.isError,flag.isFetching,flag.isPending]);
  const searchBook=React.useCallback((value:string)=>{setBookSearch(value);if(value!=="")capturePeople("people_book_search_used",{surface:"book_sheet",hasSearch:true})},[]);
  const openPerson=(p:BrandPersonSummary)=>router.push(`/(tabs)/people/${p.personId}` as never);
  const openGroup=async(entry:AudienceListEntry)=>{capturePeople("people_group_opened",{surface:groupsOpen?"groups_sheet":"page",groupKind:entry.kind});const kind=entry.kind==="brand_buyers"?"brand":"event";const target=entry.kind==="brand_buyers"?entry.brand_id:entry.event_id;if(target===null)return;if(entry.audience_id!==null){router.push(`/marketing/campaigns/compose?audience=${kind}:${target}` as never);return}if(user===null)return;setCreatingKey(entry.client_key);try{if(entry.kind==="brand_buyers")await ensureBrandBuyersAudience({account_id:user.id,brand_id:entry.brand_id});else await ensureEventBuyersAudience({account_id:user.id,brand_id:entry.brand_id,event_id:target});router.push(`/marketing/campaigns/compose?audience=${kind}:${target}` as never)}catch{setToast({message:"Couldn't open this group. Try again in a moment.",kind:"error"})}finally{setCreatingKey(null)}};
  const addDone=(result:AddBrandPersonResult)=>{if(result.outcome==="review"){capturePeople("people_add_review_required",{surface:"add_sheet",result:"review"});return}capturePeople("people_add_completed",{surface:"add_sheet",result:result.outcome});setToast({message:result.outcome==="created"?"Person added.":result.outcome==="updated"?"Existing person updated.":"This person is already in your book.",kind:"success"})};
  if(brand===null)return <View style={s.center}><EmptyState title="Choose a brand to view People." description="Select a brand from the switcher above."/></View>;
  if(book.kind==="forbidden"||role.isError)return <View style={s.center}><EmptyState title="You don’t have access to People." description="A marketing manager or brand admin can open this page."/></View>;
  const preview=book.rows.slice(0,3); return <View style={s.host}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text accessibilityRole="header" style={s.screenTitle}>People</Text>
    <PeopleBlock title="People you can reach" icon="target" minHeight={isWideDesktop?144:156}><DependencyStatus status="Reach unavailable" body="Total reach will appear when Followers and Extended circle are ready." testID="people-reach-unavailable"/></PeopleBlock>
    <PeopleBlock title="Your book" caption="People who gave your brand their details." count={book.kind==="success"||book.kind==="refreshing"?contacts(book.bookTotal):undefined} elevated testID="people-book-block">
      {book.kind==="authLoading"||book.kind==="roleLoading"||book.kind==="loading"?<View accessibilityLiveRegion="polite" style={s.skeletons}>{[0,1,2].map((i)=><View key={i} style={s.skeletonRow}><Skeleton width={40} height={40} radius="full"/><View style={s.skeletonCopy}><Skeleton width="48%" height={16}/><Skeleton width="68%" height={12}/></View></View>)}</View>:book.kind==="error"?<EmptyState title={online?"Couldn’t load your book.":"You’re offline. Connect to load your book."} description={online?"Check your connection and try again.":undefined} cta={online?{label:"Try again",onPress:async()=>{await book.refetch()},variant:"secondary"}:undefined}/>:preview.length===0?<EmptyState title="No one is in your book yet." description="Add a person, import contacts, or Mingla will add customers as they book."/>:<View style={book.kind==="refreshing"?s.refreshing:undefined}>{book.kind==="refreshing"?<Text style={s.status}>Updating…</Text>:null}{book.kind==="offlineStale"?<Text style={s.status}>Offline — showing saved contacts.</Text>:null}{preview.map((p)=><PeopleRow key={p.personId} person={p} onPress={()=>openPerson(p)}/>)}</View>}
      <View style={s.actions}><View style={actionCell}><Button label="Add" leadingIcon="plus" fullWidth accentColor={accent.warm} disabled={!authorized||!online} onPress={()=>{capturePeople("people_add_opened",{surface:"page"});setAddOpen(true)}}/></View><View style={actionCell}>{importEnabled?<Button label="Import" leadingIcon="upload" variant="secondary" fullWidth onPress={()=>{capturePeople("people_import_selected",{surface:"page",dependency:"import",dependencyState:"available"});router.push(`/(tabs)/people/import?returnTo=marketingPeople&brandId=${brand.id}` as never)}}/>:<DependencyStatus status="Import unavailable" body="Contact import is not available yet." testID="people-import-unavailable"/>}</View><View style={actionCell}><DependencyStatus status="Export unavailable" body="Book export is coming soon." testID="people-export-unavailable"/></View><View style={actionCell}><Button label="See all" trailingIcon="chevR" variant="secondary" fullWidth disabled={!book.hasResolved||book.kind==="error"} onPress={()=>{capturePeople("people_book_opened",{surface:"book_sheet"});setBookOpen(true)}}/></View></View>
    </PeopleBlock>
    <View style={isWideDesktop?s.dependencyRow:s.dependencyColumn}><View style={s.dependencyCell}><PeopleBlock title="Followers" icon="users" minHeight={136}><DependencyStatus status="Unavailable" body="Follower reach will appear when privacy-safe brand access is ready." testID="people-followers-unavailable"/></PeopleBlock></View><View style={s.dependencyCell}><PeopleBlock title="Extended circle" icon="branch" minHeight={136}><DependencyStatus status="Unavailable" body="Extended circle will appear when privacy-safe reach is ready." testID="people-extended-unavailable"/></PeopleBlock></View></View>
    <PeopleBlock title="Groups" caption="Buyer groups that update automatically." testID="people-groups-block">{!groups.hasResolved&&!groups.isError?<View testID="people-groups-skeleton" style={s.skeletons}>{[0,1,2].map((i)=><Skeleton key={i} width="100%" height={76} radius="lg"/>)}</View>:groups.isError?<EmptyState title="Couldn’t load groups." cta={{label:"Try again",onPress:async()=>{await groups.refetch()},variant:"secondary"}}/>:groups.entries.length===0?<EmptyState title="No buyer groups yet."/>:<>{groups.entries.slice(0,3).map((entry)=>{const reach=groups.reach.has(entry.client_key)?groups.reach.get(entry.client_key):undefined;return <AudienceCard key={entry.client_key} entry={entry} reach={reach} onPress={openGroup} isCreating={creatingKey===entry.client_key}/>})}{groups.entries.length>3?<Button label="See all" trailingIcon="chevR" variant="secondary" onPress={()=>setGroupsOpen(true)}/>:null}</>}</PeopleBlock>
  </ScrollView><BookSheet visible={bookOpen} onClose={()=>setBookOpen(false)} query={sheetBook} onSelect={openPerson} onSearch={searchBook}/><GroupsSheet visible={groupsOpen} onClose={()=>setGroupsOpen(false)} entries={groups.entries} reach={groups.reach} creatingKey={creatingKey} onPress={openGroup}/><AddPersonSheet visible={addOpen} onClose={()=>setAddOpen(false)} brandId={brand.id} online={online} authorized={authorized} onCompleted={addDone}/><View style={s.toast}><Toast visible={toast!==null} kind={toast?.kind??"success"} message={toast?.message??""} onDismiss={()=>setToast(null)}/></View></View>
}
const s=StyleSheet.create({host:{flex:1,backgroundColor:canvas.discover},content:{paddingHorizontal:spacing.md,paddingTop:spacing.md,paddingBottom:120,gap:spacing.lg,maxWidth:960,width:"100%",alignSelf:"center"},screenTitle:{...typography.h2,color:text.primary},center:{flex:1,backgroundColor:canvas.discover,justifyContent:"center"},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},dependencyRow:{flexDirection:"row",gap:spacing.lg},dependencyColumn:{gap:spacing.lg},dependencyCell:{flex:1,minWidth:0},skeletons:{gap:spacing.sm},skeletonRow:{minHeight:64,flexDirection:"row",alignItems:"center",gap:spacing.sm},skeletonCopy:{flex:1,gap:spacing.xs},refreshing:{opacity:.72},status:{...typography.bodySm,color:text.tertiary},toast:{position:"absolute",top:spacing.md,left:spacing.md,right:spacing.md,zIndex:100}})
