import React from "react"; import { ScrollView,StyleSheet,Text,View } from "react-native";
import type { BrandPersonSummary } from "../../types/people"; import { spacing,text,typography } from "../../constants/designSystem"; import { Avatar } from "../ui/Avatar"; import { EmptyState } from "../ui/EmptyState"; import { GlassCard } from "../ui/GlassCard"; import { Icon } from "../ui/Icon"; import { Skeleton } from "../ui/Skeleton";
export function PersonDetailView({person,loading,error,onRetry}:{person:BrandPersonSummary|null;loading:boolean;error:"not_found"|"forbidden"|"error"|null;onRetry:()=>void}):React.ReactElement{
 if(loading)return <View style={s.loading}><Skeleton width={84} height={84} radius="full"/><Skeleton width="48%" height={28}/><Skeleton width="100%" height={120}/></View>;
 if(error==="forbidden")return <EmptyState title="You don’t have access to People." description="A marketing manager or brand admin can open this page."/>;
 if(error==="not_found")return <EmptyState title="This person isn’t in your book." description="They may have been merged or removed."/>;
 if(error||!person)return <EmptyState title="Couldn’t load this person." cta={{label:"Try again",onPress:onRetry,variant:"secondary"}}/>;
 return <ScrollView contentContainerStyle={s.content}><View style={s.hero}><Avatar name={person.displayName} photo={person.avatarUrl??undefined} size="hero"/><Text accessibilityRole="header" style={s.name}>{person.displayName}</Text></View><GlassCard contentStyle={s.card}><Text style={s.heading}>Contact details</Text>{person.contacts.map((c)=><View key={c.id} style={s.row}><Icon name={c.channel==="email"?"mail":"phone"} size={20} color={text.secondary}/><View style={s.rowCopy}><Text style={s.value} numberOfLines={2}>{c.value}</Text>{c.isPrimary?<Text style={s.primary}>Primary</Text>:null}</View></View>)}</GlassCard>{person.suppressions.length?<GlassCard contentStyle={s.card}><Text style={s.heading}>Marketing preferences</Text>{person.suppressions.map((x)=><View key={`${x.channel}:${x.scope}`} style={s.row}><Icon name="shield" size={20} color={text.secondary}/><Text style={s.value}>{x.channel==="email"?"Email marketing suppressed":"Text marketing suppressed"}</Text></View>)}</GlassCard>:null}</ScrollView>
}
const s=StyleSheet.create({content:{paddingHorizontal:spacing.md,paddingTop:spacing.lg,paddingBottom:120,gap:spacing.lg,maxWidth:720,width:"100%",alignSelf:"center"},loading:{padding:spacing.lg,gap:spacing.md,alignItems:"center"},hero:{alignItems:"center",gap:spacing.sm},name:{...typography.h1,color:text.primary,textAlign:"center"},card:{gap:spacing.sm},heading:{...typography.h3,color:text.primary},row:{minHeight:56,flexDirection:"row",alignItems:"center",gap:spacing.sm},rowCopy:{flex:1},value:{...typography.body,color:text.primary},primary:{...typography.caption,color:text.secondary}})
