/**
 * Issue #1876 — TESTER ADVERSARIAL suite.
 *
 * The implementor's two suites prove the right NODE is CREATED. This one asks
 * the two questions they cannot: can a human SEE it, and can it ever appear
 * over a working app? Both were answered by driving the EXACT shipped `<head>`
 * bytes in a real Chromium against the real deployed shell, and both answers
 * were bad. This suite encodes those answers so they can never regress.
 *
 * ---------------------------------------------------------------------------
 * SECTION V — THE CARD IS RENDERED BELOW THE FOLD, ON A PAGE THAT CANNOT SCROLL
 * ---------------------------------------------------------------------------
 * The card is appended to `document.body` as a static-flow sibling AFTER
 * `#root`. The deployed shell ships react-native-web's recommended reset in
 * `<style id="expo-reset">`, verbatim:
 *
 *     html, body { height: 100%; }
 *     body       { overflow: hidden; }
 *     #root      { display: flex; height: 100%; flex: 1; }
 *
 * An EMPTY `#root` therefore still occupies the whole viewport, so a static
 * sibling placed after it starts at 100vh + the card's own 15vh top margin —
 * below the fold by construction. And `body { overflow: hidden }` propagates to
 * the viewport (the root element's own overflow is `visible`), so the user
 * cannot scroll down to it.
 *
 * Measured in Chromium against the real shipped shell, cooldown primed and all
 * three entry chunks 404ing — i.e. the exact scenario SC-8 describes:
 *
 *   viewport         card top   card visible px   wheel   touch drag   keyboard
 *   iPhone 13 390x664   772          0             0 px      0 px        0 px
 *   Pixel 5   393x727   844          0             0 px      0 px        0 px
 *   desktop  1280x800   928          0             0 px       n/a        0 px
 *
 * Only a programmatic `window.scrollTo` reached it, and nothing calls that. The
 * viewport screenshot of the "fixed" page is a pure white rectangle — pixel for
 * pixel the bug this issue is titled after. A DOM-presence assertion passes on
 * that page, which is exactly the green-CI-and-broken-product inversion.
 *
 * V.1 pins the structural fact (static sibling after a full-height `#root`).
 * V.2 requires the card to be reachable. It deliberately accepts ANY of the
 * three constructions that actually achieve it rather than mandating one:
 * viewport-anchoring the host, neutralising the empty `#root`, or restoring
 * scroll and bringing the card into view.
 *
 * ---------------------------------------------------------------------------
 * SECTION F — THE 1500 ms GUARD IS A SNAPSHOT, NOT AN INVARIANT
 * ---------------------------------------------------------------------------
 * `#root`-empty is tested exactly once, when the timer fires, and the card is
 * never removed. Measured boundary, same Chromium harness, mount time relative
 * to the suppression event:
 *
 *   mount at 1400 ms -> no card      mount at 1501 ms -> card, and it STAYS
 *   mount at 1490 ms -> no card      mount at 1600 ms -> card, and it STAYS
 *   mount at 1499 ms -> no card      mount at 2500 ms -> card, and it STAYS
 *                                    mount at 5000 ms -> card, and it STAYS
 *
 * The boundary is exact and correct at 1500 ms. What is wrong is what happens
 * on the far side of it: a slow-but-successful boot that commits at 1501 ms
 * gets a permanent "this page didn't finish loading" card sitting over a
 * perfectly healthy app, with no path back. Today that defect is masked by
 * Section V — the false-positive card is below the fold too — so fixing V
 * without fixing F turns an invisible false positive into a visible one.
 *
 * F.2 is the contract: once the app mounts, the card must go.
 *
 * ---------------------------------------------------------------------------
 * SECTION D — THE INVERSE REGRESSION: DEEP LINKS MUST NEVER 404
 * ---------------------------------------------------------------------------
 * Over-excluding is worse than under-excluding: a route that stops reaching the
 * shell is a dead public link. #1485's A.6 guards this, but only against the
 * `_expo/static/` alternate by name, so it did not widen when `assets/` joined.
 * D.1 is generic over EVERY alternate in the shipped alternation, derived from
 * the real `app/` tree, so a fourth alternate is covered the day it lands.
 *
 * ---------------------------------------------------------------------------
 * SECTION E — RESIDUAL PATH SHAPES, PINNED SO THEY STAY VISIBLE
 * ---------------------------------------------------------------------------
 * Probed live on production 2026-08-11: `/Assets/…`, `/%61ssets/…` and the
 * bare `/assets` tree root all still resolve to the shell. None is generated by
 * a browser or by this app, so none is a defect to fix here — but they are
 * holes in "the build-output tree never answers with HTML", and pinning them is
 * how they stay visible rather than being rediscovered a third time.
 *
 * Fails-on-revert: V.2 and F.2 fail against `fe76b973a` (the state that shipped
 * this issue's fix) and pass only once the card is reachable and self-clearing.
 * D.1 fails the moment an alternate shadows a real route; E fails on drift.
 */

import { readdirSync, readFileSync } from "fs";
import path from "path";

import { afterEach, beforeEach, describe, expect, jest, test } from "@jest/globals";

const BUSINESS_ROOT = path.join(__dirname, "..");
const INJECT_PATH = path.join(BUSINESS_ROOT, "scripts", "inject-mobile-blur-css.mjs");
const APP_DIR = path.join(BUSINESS_ROOT, "app");

const injectSource = readFileSync(INJECT_PATH, "utf8");
const vercel = JSON.parse(readFileSync(path.join(BUSINESS_ROOT, "vercel.json"), "utf8")) as {
  rewrites: { source: string; destination: string }[];
};
const catchAll = vercel.rewrites[vercel.rewrites.length - 1];
const COMPILED_CATCH_ALL = new RegExp(`^(?:${catchAll.source})$`);

const BOOT_ERROR_ID = "mingla-boot-error";
const SHARED_KEY = "mingla:last-chunk-reload";
const CHUNK_URL = "/_expo/static/js/web/index-c71bd65d4564bece548e38b8d5512d1e.js";

// ---------------------------------------------------------------------------
// Independent synthetic DOM. Written from scratch rather than reused, and
// deliberately RICHER than the implementor's: nodes can be removed, and a
// MutationObserver exists, so any of the plausible fixes for F.2 can be
// expressed and observed instead of being assumed away by a harness that
// cannot represent them.
// ---------------------------------------------------------------------------

type Node = {
  tagName: string;
  id: string;
  type: string;
  textContent: string;
  style: { cssText: string };
  attributes: Record<string, string>;
  childNodes: Node[];
  parentNode: Node | null;
  onclick: null | (() => void);
  setAttribute: (name: string, value: string) => void;
  appendChild: (child: Node) => Node;
  removeChild: (child: Node) => Node;
  remove: () => void;
  scrollIntoView: () => void;
};

const observers: { target: Node; cb: () => void }[] = [];

function notify(node: Node | null): void {
  for (let cursor = node; cursor !== null; cursor = cursor.parentNode) {
    for (const entry of observers) if (entry.target === cursor) entry.cb();
  }
}

function makeNode(tagName: string): Node {
  const node: Node = {
    tagName,
    id: "",
    type: "",
    textContent: "",
    style: { cssText: "" },
    attributes: {},
    childNodes: [],
    parentNode: null,
    onclick: null,
    setAttribute: (name, value) => {
      node.attributes[name] = value;
    },
    appendChild: (child) => {
      child.parentNode = node;
      node.childNodes.push(child);
      notify(node);
      return child;
    },
    removeChild: (child) => {
      const at = node.childNodes.indexOf(child);
      if (at >= 0) node.childNodes.splice(at, 1);
      child.parentNode = null;
      notify(node);
      return child;
    },
    remove: () => {
      if (node.parentNode !== null) node.parentNode.removeChild(node);
    },
    scrollIntoView: () => {
      scrolledIntoView.push(node.id);
    },
  };
  return node;
}

let scrolledIntoView: string[] = [];

function findById(node: Node, id: string): Node | null {
  if (node.id === id) return node;
  for (const child of node.childNodes) {
    const hit = findById(child, id);
    if (hit !== null) return hit;
  }
  return null;
}

/** The EXACT `<script>` bytes the build injects — evaluated, never grepped. */
function shippedScriptBody(): string {
  const literal = injectSource.match(/const CHUNK_RECOVERY_SCRIPT =\s*(`[^`]*`);/);
  if (literal === null) throw new Error("CHUNK_RECOVERY_SCRIPT template literal not found");
  const named = (name: string): string => {
    const hit = injectSource.match(new RegExp(`const ${name} = "([^"]*)";`));
    if (hit === null) throw new Error(`missing const ${name}`);
    return hit[1];
  };
  const cooldown = injectSource.match(/const CHUNK_RECOVERY_COOLDOWN_MS = ([0-9_]+);/);
  if (cooldown === null) throw new Error("missing const CHUNK_RECOVERY_COOLDOWN_MS");
  const build = new Function(
    "CHUNK_RECOVERY_MARKER",
    "CHUNK_RECOVERY_KEY",
    "CHUNK_RECOVERY_COOLDOWN_MS",
    `return ${literal[1]};`,
  ) as (marker: string, key: string, cooldown: number) => string;
  return build(named("CHUNK_RECOVERY_MARKER"), named("CHUNK_RECOVERY_KEY"), Number(cooldown[1]))
    .replace(/^<script[^>]*>/, "")
    .replace(/<\/script>$/, "");
}

const SCRIPT_BODY = shippedScriptBody();

const realWindow = (global as unknown as { window?: unknown }).window;

beforeEach(() => {
  jest.useFakeTimers();
  jest.setSystemTime(1_700_000_000_000);
  observers.length = 0;
  scrolledIntoView = [];
});

afterEach(() => {
  jest.useRealTimers();
  (global as unknown as { window?: unknown }).window = realWindow;
  jest.clearAllMocks();
});

type Harness = {
  body: Node;
  root: () => Node | null;
  card: () => Node | null;
  reload: jest.Mock;
  /** Fire a genuine capture-phase resource error for a chunk URL. */
  fail: (src?: string) => void;
  /** React commits its first render into `#root`. */
  mountApp: () => void;
};

/** Boots the shipped bytes with the cooldown ALREADY spent, i.e. suppression. */
function bootWithCooldownSpent(): Harness {
  const listeners = new Map<string, ((event: unknown) => void)[]>();
  const store = new Map<string, string>([[SHARED_KEY, String(Date.now())]]);
  const reload = jest.fn();

  const body = makeNode("body");
  const rootNode = Object.assign(makeNode("div"), { id: "root" });
  body.appendChild(rootNode);

  const doc = {
    body,
    createElement: (tag: string) => makeNode(tag),
    getElementById: (id: string) => findById(body, id),
    addEventListener: () => undefined,
    querySelector: (sel: string) => findById(body, sel.replace(/^#/, "")),
  };

  const fakeWindow: Record<string, unknown> = {
    addEventListener: (type: string, listener: (event: unknown) => void): void => {
      const existing = listeners.get(type) ?? [];
      existing.push(listener);
      listeners.set(type, existing);
    },
    document: doc,
    location: { reload, replace: jest.fn(), assign: jest.fn(), href: "https://host.usemingla.com/checkout/abc" },
    sessionStorage: {
      getItem: (key: string): string | null => store.get(key) ?? null,
      setItem: (key: string, value: string): void => void store.set(key, value),
      removeItem: (key: string): void => void store.delete(key),
    },
    setTimeout: ((handler: () => void, delay?: number) => setTimeout(handler, delay)) as typeof setTimeout,
    setInterval: ((handler: () => void, delay?: number) => setInterval(handler, delay)) as typeof setInterval,
    clearInterval: ((handle: never) => clearInterval(handle)) as typeof clearInterval,
    clearTimeout: ((handle: never) => clearTimeout(handle)) as typeof clearTimeout,
    requestAnimationFrame: ((handler: () => void) => setTimeout(handler, 16)) as unknown,
    MutationObserver: class {
      private readonly cb: () => void;
      constructor(cb: () => void) {
        this.cb = cb;
      }
      observe(target: Node): void {
        observers.push({ target, cb: this.cb });
      }
      disconnect(): void {
        for (let i = observers.length - 1; i >= 0; i -= 1) {
          if (observers[i].cb === this.cb) observers.splice(i, 1);
        }
      }
      takeRecords(): unknown[] {
        return [];
      }
    },
  };

  (global as unknown as { window?: unknown }).window = fakeWindow;
  const quietConsole = { warn: jest.fn(), error: jest.fn(), log: jest.fn() };
  new Function("window", "console", SCRIPT_BODY)(fakeWindow, quietConsole);

  return {
    body,
    root: () => findById(body, "root"),
    card: () => findById(body, BOOT_ERROR_ID),
    reload,
    fail: (src = CHUNK_URL) => {
      const registered = listeners.get("error") ?? [];
      expect(registered.length).toBeGreaterThan(0);
      for (const listener of registered) listener({ target: { src } });
    },
    mountApp: () => {
      const root = findById(body, "root");
      if (root === null) throw new Error("#root vanished");
      root.appendChild(Object.assign(makeNode("div"), { id: "app-shell" }));
    },
  };
}

// ---------------------------------------------------------------------------
// V — REACHABILITY
// ---------------------------------------------------------------------------

describe("#1876 V — the terminal card must be somewhere the user can actually see", () => {
  test("V.1 — it is a static-flow sibling appended AFTER the full-height #root", () => {
    // The structural premise of the whole section. If this ever stops being
    // true the measurements in the header comment stop applying and V.2 must be
    // re-derived rather than trusted.
    const h = bootWithCooldownSpent();
    h.fail();
    jest.advanceTimersByTime(1500);

    const card = h.card();
    expect(card).not.toBeNull();
    expect(h.body.childNodes.map((n) => n.id)).toEqual(["root", BOOT_ERROR_ID]);
    expect(card?.parentNode).toBe(h.body);
  });

  test("V.2 — the card is reachable in the viewport, not stranded below the fold", () => {
    const h = bootWithCooldownSpent();
    h.fail();
    jest.advanceTimersByTime(1500);

    const card = h.card();
    expect(card).not.toBeNull();
    const cardCss = card?.style.cssText ?? "";
    const rootCss = h.root()?.style.cssText ?? "";

    // Any ONE of these makes the card reachable given the shipped expo-reset.
    // The suite does not care which is chosen, only that one of them is.
    const viewportAnchored = /position\s*:\s*fixed/i.test(cardCss);
    const emptyRootNeutralised =
      /display\s*:\s*none/i.test(rootCss) || /height\s*:\s*(0|auto)/i.test(rootCss);
    const broughtIntoView =
      scrolledIntoView.includes(BOOT_ERROR_ID) ||
      /overflow\s*:\s*(auto|scroll|visible)/i.test(h.body.style.cssText);

    expect({
      viewportAnchored,
      emptyRootNeutralised,
      broughtIntoView,
      cardCss,
      note:
        "measured in Chromium on the real shell: card top 772px in a 664px viewport, " +
        "0 visible pixels, and wheel/touch/keyboard all scrolled 0px because " +
        "body{overflow:hidden} propagates to the viewport",
    }).toMatchObject({
      // At least one reachability construction must be present.
      ...(viewportAnchored || emptyRootNeutralised || broughtIntoView
        ? {}
        : { viewportAnchored: true }),
    });
    expect(viewportAnchored || emptyRootNeutralised || broughtIntoView).toBe(true);
  });

  test("V.3 — whatever makes it reachable must not cover a mounted app", () => {
    // The mirror of V.2: a viewport-anchored overlay is only acceptable while
    // #root is empty. If the card is anchored over the app it must still be
    // gated on the same emptiness test, which F.2 enforces.
    const h = bootWithCooldownSpent();
    h.mountApp(); // React is already up before the failure
    h.fail();
    jest.advanceTimersByTime(5000);
    expect(h.card()).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// F — FALSE POSITIVES
// ---------------------------------------------------------------------------

describe("#1876 F — the card must never end up sitting over a working app", () => {
  test("F.1 — the emptiness test is taken at 1500 ms, and 1499 ms is still safe", () => {
    const h = bootWithCooldownSpent();
    h.fail();
    jest.advanceTimersByTime(1499);
    expect(h.card()).toBeNull(); // nothing has fired yet
    h.mountApp(); // a slow-but-successful boot commits with 1 ms to spare
    jest.advanceTimersByTime(1);
    expect(h.card()).toBeNull();
    jest.advanceTimersByTime(10_000);
    expect(h.card()).toBeNull();
  });

  test("F.2 — a boot that commits AFTER the guard fires must clear the card", () => {
    // Chromium-measured: at 1501 ms the card appears and never leaves. On a
    // slow phone the entry bundle can commit seconds after a suppressed lazy
    // chunk error, and the user is then told the page did not load while
    // looking at a page that did. The emptiness test has to be an invariant
    // that holds for as long as the card is on screen, not a single sample.
    const h = bootWithCooldownSpent();
    h.fail();
    jest.advanceTimersByTime(1501);
    expect(h.card()).not.toBeNull(); // the guard fired while #root was empty

    h.mountApp(); // React commits 1 ms late
    jest.advanceTimersByTime(5000);

    expect(h.card()).toBeNull();
  });

  test("F.3 — clearing the card must not disturb the app that displaced it", () => {
    const h = bootWithCooldownSpent();
    h.fail();
    jest.advanceTimersByTime(1501);
    h.mountApp();
    jest.advanceTimersByTime(5000);

    const root = h.root();
    expect(root).not.toBeNull();
    expect(root?.childNodes.map((n) => n.id)).toEqual(["app-shell"]);
    expect(h.reload).not.toHaveBeenCalled(); // no reload-loop was introduced
  });

  test("F.4 — the arm latch must not be spent by a failure the app survived", () => {
    // A suppressed LAZY-route failure while React is alive correctly renders no
    // card. It must not also burn the one-shot latch, or a genuine entry-bundle
    // blank page later in the same document gets nothing at all.
    const h = bootWithCooldownSpent();
    h.mountApp();
    h.fail(); // lazy chunk dies, app survives
    jest.advanceTimersByTime(5000);
    expect(h.card()).toBeNull();

    // The app is torn back down to an empty #root and fails again.
    const root = h.root();
    while (root !== null && root.childNodes.length > 0) root.removeChild(root.childNodes[0]);
    h.fail();
    jest.advanceTimersByTime(5000);
    expect(h.card()).not.toBeNull();
  });
});

// ---------------------------------------------------------------------------
// D — THE INVERSE REGRESSION
// ---------------------------------------------------------------------------

/** Every alternate inside the shipped `(?!…)` lookahead, in order. */
const ALTERNATES = (/\(\?!([^)]+)\)/.exec(catchAll.source)?.[1] ?? "").split("|");

function walkRoutes(dir: string, rel = ""): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const childRel = rel === "" ? entry.name : `${rel}/${entry.name}`;
    if (entry.isDirectory()) out.push(...walkRoutes(path.join(dir, entry.name), childRel));
    else if (/\.tsx?$/.test(entry.name) && !entry.name.startsWith("+")) out.push(childRel);
  }
  return out;
}

describe("#1876 D — over-excluding would 404 live deep links, so prove it cannot", () => {
  test("D.1 — no alternate shadows any real route, generically over the whole list", () => {
    // #1485's A.6 hard-codes `_expo/static/`, so it did not widen when
    // `assets/` joined and will not widen for the next one either. This is
    // derived from the alternation itself.
    expect(ALTERNATES.length).toBeGreaterThanOrEqual(3);
    const routeFiles = walkRoutes(APP_DIR);
    expect(routeFiles.length).toBeGreaterThan(30); // guard against a walker no-op

    const firstSegments = new Set(
      routeFiles
        .map((file) => file.split("/")[0].replace(/\.tsx?$/, ""))
        .filter((segment) => !segment.startsWith("(") && !segment.startsWith("_")),
    );

    const collisions: string[] = [];
    for (const alternate of ALTERNATES) {
      const prefix = alternate.replace(/\$$/, "").replace(/\/$/, "");
      for (const segment of firstSegments) {
        if (segment === prefix) collisions.push(`${alternate} shadows app/${segment}`);
      }
    }
    expect(collisions).toEqual([]);
  });

  test("D.2 — every top-level route segment still reaches the SPA shell", () => {
    const routeFiles = walkRoutes(APP_DIR);
    const segments = [
      ...new Set(
        routeFiles
          .map((file) => file.split("/")[0].replace(/\.tsx?$/, ""))
          .filter((segment) => !segment.startsWith("(")),
      ),
    ].sort();

    const notCaught = segments.filter((segment) => !COMPILED_CATCH_ALL.test(`/${segment}`));
    expect(notCaught).toEqual([]);
  });

  test("D.3 — the alternates that exist correspond to build output, not to routes", () => {
    expect(ALTERNATES).toContain("_expo/static/");
    expect(ALTERNATES).toContain("assets/");
    // Anything ending in `/` is a directory prefix; anything else must be an
    // exact-match `$` form, which cannot swallow a subtree by accident.
    for (const alternate of ALTERNATES) {
      expect([alternate, alternate.endsWith("/") || alternate.endsWith("$")]).toEqual([
        alternate,
        true,
      ]);
    }
  });
});

// ---------------------------------------------------------------------------
// E — RESIDUAL HOLES, PINNED
// ---------------------------------------------------------------------------

describe("#1876 E — path shapes the exclusion does NOT cover (pinned, not fixed)", () => {
  test("E.1 — case and percent-encoded variants still reach the shell", () => {
    // Probed live 2026-08-11: all three returned `200 text/html` on production
    // before this change, and the literal alternation does not address them.
    // No browser and nothing in this app emits them, so they are documented
    // rather than fixed — but they are holes in "the build-output tree never
    // answers with HTML" and must not be rediscovered a third time.
    for (const url of [
      "/Assets/does-not-exist-0000.png",
      "/ASSETS/does-not-exist-0000.png",
      "/%61ssets/does-not-exist-0000.png",
      "/assets%2Fdoes-not-exist-0000.png",
    ]) {
      expect([url, COMPILED_CATCH_ALL.test(url)]).toEqual([url, true]);
    }
  });

  test("E.2 — the bare tree root `/assets` is not covered by the `assets/` prefix", () => {
    expect(COMPILED_CATCH_ALL.test("/assets")).toBe(true);
    expect(COMPILED_CATCH_ALL.test("/assets/")).toBe(false);
  });

  test("E.3 — a nested `assets/` segment is correctly NOT excluded", () => {
    // The inverse guard: these are real SPA routes and must keep resolving.
    for (const url of ["/x/assets/y.png", "/venue/assets/create", "/b/assets/v/rooftop"]) {
      expect([url, COMPILED_CATCH_ALL.test(url)]).toEqual([url, true]);
    }
  });

  test("E.4 — the two bundle-referenced assets that are ABSENT from the deploy will now 404", () => {
    // Live probe 2026-08-11: both are referenced by the shipped entry bundle
    // and both returned `200 text/html` — they are not in the export at all.
    // After this change they become honest 404s. Recorded so the new 404s in
    // production logs are expected, not a fresh incident.
    for (const url of ["/assets/images/favicon.png", "/assets/images/icon.png"]) {
      expect([url, COMPILED_CATCH_ALL.test(url)]).toEqual([url, false]);
    }
  });
});
