/**
 * Platform Cards - Centralized card data for all user roles
 * 
 * All live cards shown to explorers come from this centralized store.
 * Cards can be created by:
 * 1. Curators for the platform
 * 2. Businesses for the platform
 * 3. Curators for businesses (on behalf of businesses)
 */

export interface PlatformCard {
  id: string;
  title: string;
  category: string;
  description: string;
  image: string;
  images?: string[];
  location: string;
  venue: string;
  price: string;
  priceRange?: string;
  duration: string;
  rating: number;
  reviews: number;
  matchScore?: number;
  tags?: string[];
  highlights?: string[];
  
  // Card Status & Workflow
  status: 'draft' | 'in-review' | 'live' | 'returned';
  
  // Ownership & Attribution
  createdBy: string; // User ID of creator
  createdByRole: 'curator' | 'business' | 'qa' | 'api';
  createdByName: string;
  businessId?: string; // If created for a specific business
  businessName?: string;
  curatorId?: string; // If created by curator for a business
  isApiGenerated?: boolean; // If generated by AI from explorer query
  
  // Timestamps
  createdAt: string;
  lastEdited: string;
  publishedAt?: string;
  
  // Stats (for live cards)
  views?: number;
  likes?: number;
  saves?: number;
  shares?: number;
  totalSales?: number;
  
  // QA moderation
  feedback?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  flaggedForReview?: boolean;
  flagReason?: string;
  flaggedBy?: string;
  flaggedAt?: string;
  
  // Additional metadata
  availability?: any;
  packages?: any[];
  policies?: any;
  routeSteps?: any[];
  totalDuration?: number;
}

/**
 * Seed data with cards from different creators
 */
export const PLATFORM_CARDS_SEED: PlatformCard[] = [
  // CURATOR-CREATED CARDS FOR THE PLATFORM
  {
    id: 'card-curator-1',
    title: 'Sunset Rooftop Wine Tasting',
    category: 'sipChill',
    description: 'Experience an exquisite selection of local and imported wines while enjoying breathtaking sunset views from our rooftop terrace. Expert sommeliers guide you through each tasting.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400'],
    location: 'Downtown SF',
    venue: 'The Vista Lounge',
    price: '$45-60',
    priceRange: '$45-60',
    duration: '2 hours',
    rating: 4.8,
    reviews: 234,
    matchScore: 95,
    tags: ['Wine', 'Sunset', 'Views', 'Romantic'],
    highlights: ['Expert sommeliers', 'Panoramic city views', '6-wine flight'],
    status: 'live',
    createdBy: 'curator-001',
    createdByRole: 'curator',
    createdByName: 'Sarah Martinez',
    createdAt: '2025-01-10T10:00:00Z',
    lastEdited: '2025-01-10T10:00:00Z',
    publishedAt: '2025-01-12T14:00:00Z',
    views: 1234,
    likes: 89,
    saves: 45,
    shares: 12,
    totalSales: 4500
  },
  {
    id: 'card-curator-2',
    title: 'Morning Yoga at Golden Gate Park',
    category: 'wellness',
    description: 'Start your day with mindful movement in nature. All levels welcome. Mats provided.',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    images: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400'],
    location: 'Golden Gate Park',
    venue: 'Meadow Yoga Collective',
    price: '$20-30',
    priceRange: '$20-30',
    duration: '1.5 hours',
    rating: 4.9,
    reviews: 156,
    matchScore: 88,
    tags: ['Yoga', 'Wellness', 'Outdoor', 'Morning'],
    highlights: ['All levels welcome', 'Mats provided', 'Meditation included'],
    status: 'live',
    createdBy: 'curator-001',
    createdByRole: 'curator',
    createdByName: 'Sarah Martinez',
    createdAt: '2025-01-08T09:00:00Z',
    lastEdited: '2025-01-08T09:00:00Z',
    publishedAt: '2025-01-09T08:00:00Z',
    views: 892,
    likes: 67,
    saves: 34,
    shares: 8,
    totalSales: 1800
  },

  // BUSINESS-CREATED CARDS FOR THE PLATFORM
  {
    id: 'card-business-1',
    title: 'Chef\'s Table Tasting Menu',
    category: 'diningExp',
    description: '8-course seasonal tasting menu featuring locally-sourced ingredients. Wine pairing available.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400'],
    location: 'Mission District',
    venue: 'Le Jardin',
    price: '$125-165',
    priceRange: '$125-165',
    duration: '3 hours',
    rating: 4.9,
    reviews: 312,
    matchScore: 92,
    tags: ['Fine Dining', 'Tasting Menu', 'Wine Pairing', 'Seasonal'],
    highlights: ['8-course menu', 'Local ingredients', 'Chef interaction'],
    status: 'live',
    createdBy: 'business-le-jardin',
    createdByRole: 'business',
    createdByName: 'Le Jardin Restaurant',
    businessId: 'business-le-jardin',
    businessName: 'Le Jardin',
    createdAt: '2025-01-05T11:00:00Z',
    lastEdited: '2025-01-05T11:00:00Z',
    publishedAt: '2025-01-06T10:00:00Z',
    views: 2103,
    likes: 145,
    saves: 78,
    shares: 23,
    totalSales: 12500
  },
  {
    id: 'card-business-2',
    title: 'Artisan Pottery Workshop',
    category: 'creative',
    description: 'Create your own ceramic masterpiece in our professional studio. All materials and firing included.',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
    images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400'],
    location: 'SOMA',
    venue: 'Clay & Co Studio',
    price: '$85-110',
    priceRange: '$85-110',
    duration: '2.5 hours',
    rating: 4.7,
    reviews: 189,
    matchScore: 90,
    tags: ['Pottery', 'Workshop', 'Hands-On', 'Art'],
    highlights: ['Professional instruction', 'All materials included', 'Take home your piece'],
    status: 'live',
    createdBy: 'business-clay-co',
    createdByRole: 'business',
    createdByName: 'Clay & Co Studio',
    businessId: 'business-clay-co',
    businessName: 'Clay & Co Studio',
    createdAt: '2025-01-07T14:00:00Z',
    lastEdited: '2025-01-07T14:00:00Z',
    publishedAt: '2025-01-08T09:00:00Z',
    views: 1456,
    likes: 98,
    saves: 56,
    shares: 15,
    totalSales: 8500
  },

  // CURATOR-CREATED CARDS FOR BUSINESSES
  {
    id: 'card-curator-for-business-1',
    title: 'Jazz Night at The Blue Note',
    category: 'screenRelax',
    description: 'Live jazz performances every Friday and Saturday. Premium seating with table service.',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400',
    images: ['https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400'],
    location: 'SoMa',
    venue: 'The Blue Note SF',
    price: '$35-50',
    priceRange: '$35-50',
    duration: '2 hours',
    rating: 4.6,
    reviews: 267,
    matchScore: 86,
    tags: ['Jazz', 'Live Music', 'Nightlife', 'Cocktails'],
    highlights: ['Live performances', 'Table service', 'Craft cocktails'],
    status: 'live',
    createdBy: 'curator-002',
    createdByRole: 'curator',
    createdByName: 'Michael Chen',
    businessId: 'business-blue-note',
    businessName: 'The Blue Note SF',
    curatorId: 'curator-002',
    createdAt: '2025-01-06T16:00:00Z',
    lastEdited: '2025-01-06T16:00:00Z',
    publishedAt: '2025-01-07T12:00:00Z',
    views: 1678,
    likes: 112,
    saves: 67,
    shares: 19,
    totalSales: 6300
  },
  {
    id: 'card-curator-for-business-2',
    title: 'Sunset Kayaking Adventure',
    category: 'playMove',
    description: 'Paddle along the bay as the sun sets. Equipment and instruction included. Perfect for beginners!',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400'],
    location: 'Marina District',
    venue: 'Bay Adventures',
    price: '$55-75',
    priceRange: '$55-75',
    duration: '2 hours',
    rating: 4.8,
    reviews: 198,
    matchScore: 91,
    tags: ['Kayaking', 'Sunset', 'Outdoor', 'Water Sports'],
    highlights: ['Equipment provided', 'Beginner friendly', 'Sunset views'],
    status: 'live',
    createdBy: 'curator-002',
    createdByRole: 'curator',
    createdByName: 'Michael Chen',
    businessId: 'business-bay-adventures',
    businessName: 'Bay Adventures',
    curatorId: 'curator-002',
    createdAt: '2025-01-09T13:00:00Z',
    lastEdited: '2025-01-09T13:00:00Z',
    publishedAt: '2025-01-10T10:00:00Z',
    views: 1123,
    likes: 87,
    saves: 49,
    shares: 14,
    totalSales: 5500
  },
  {
    id: 'card-curator-for-business-3',
    title: 'Farm-to-Table Brunch Experience',
    category: 'casualEats',
    description: 'Weekend brunch featuring ingredients from local farms. Bottomless mimosas available.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400'],
    location: 'Hayes Valley',
    venue: 'The Farmhouse Kitchen',
    price: '$35-48',
    priceRange: '$35-48',
    duration: '1.5 hours',
    rating: 4.7,
    reviews: 223,
    matchScore: 89,
    tags: ['Brunch', 'Farm-to-Table', 'Mimosas', 'Weekend'],
    highlights: ['Local ingredients', 'Bottomless mimosas', 'Weekend only'],
    status: 'live',
    createdBy: 'curator-001',
    createdByRole: 'curator',
    createdByName: 'Sarah Martinez',
    businessId: 'business-farmhouse',
    businessName: 'The Farmhouse Kitchen',
    curatorId: 'curator-001',
    createdAt: '2025-01-11T10:00:00Z',
    lastEdited: '2025-01-11T10:00:00Z',
    publishedAt: '2025-01-12T08:00:00Z',
    views: 1567,
    likes: 103,
    saves: 61,
    shares: 17,
    totalSales: 7200
  },

  // DRAFT & IN-REVIEW CARDS (for testing workflow)
  {
    id: 'card-draft-1',
    title: 'Chocolate Making Masterclass',
    category: 'creative',
    description: 'Learn the art of chocolate making from bean to bar. Create your own custom chocolates to take home.',
    image: 'https://images.unsplash.com/photo-1646082192921-272df4780996?w=400',
    images: ['https://images.unsplash.com/photo-1646082192921-272df4780996?w=400'],
    location: 'Mission District',
    venue: 'Cacao Workshop',
    price: '$75-95',
    priceRange: '$75-95',
    duration: '3 hours',
    rating: 0,
    reviews: 0,
    tags: ['Chocolate', 'Workshop', 'Hands-On'],
    highlights: ['Bean-to-bar process', 'Take home samples', 'Expert instruction'],
    status: 'draft',
    createdBy: 'curator-001',
    createdByRole: 'curator',
    createdByName: 'Sarah Martinez',
    createdAt: '2025-01-14T09:00:00Z',
    lastEdited: '2025-01-14T12:00:00Z'
  },
  {
    id: 'card-in-review-1',
    title: 'Urban Hiking & Coffee Tour',
    category: 'stroll',
    description: 'Explore SF\'s best neighborhoods on foot, stopping at top-rated coffee shops along the way.',
    image: 'https://images.unsplash.com/photo-1445077100181-a33e9ac94db0?w=400',
    images: ['https://images.unsplash.com/photo-1445077100181-a33e9ac94db0?w=400'],
    location: 'Various SF',
    venue: 'Urban Explorers',
    price: '$45-60',
    priceRange: '$45-60',
    duration: '3 hours',
    rating: 0,
    reviews: 0,
    tags: ['Walking', 'Coffee', 'Urban Exploration'],
    highlights: ['4 neighborhoods', '5 coffee stops', 'Local guide'],
    status: 'in-review',
    createdBy: 'business-urban-explorers',
    createdByRole: 'business',
    createdByName: 'Urban Explorers',
    businessId: 'business-urban-explorers',
    businessName: 'Urban Explorers',
    createdAt: '2025-01-13T11:00:00Z',
    lastEdited: '2025-01-13T15:00:00Z',
    feedback: 'QA Review: Please add more details about the specific neighborhoods visited and accessibility information.'
  },
  {
    id: 'card-returned-1',
    title: 'Rooftop Cinema Experience',
    category: 'screenRelax',
    description: 'Watch classic films under the stars on our rooftop cinema. Gourmet popcorn and drinks available.',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    images: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400'],
    location: 'Downtown SF',
    venue: 'SkyView Cinema',
    price: '$25-35',
    priceRange: '$25-35',
    duration: '2.5 hours',
    rating: 0,
    reviews: 0,
    tags: ['Movies', 'Rooftop', 'Outdoor'],
    highlights: ['Classic films', 'Rooftop setting', 'Full bar'],
    status: 'returned',
    createdBy: 'curator-002',
    createdByRole: 'curator',
    createdByName: 'Michael Chen',
    businessId: 'business-skyview',
    businessName: 'SkyView Cinema',
    curatorId: 'curator-002',
    createdAt: '2025-01-12T14:00:00Z',
    lastEdited: '2025-01-13T09:00:00Z',
    feedback: 'QA Manager: Film schedule dates have passed. Please update with current screenings or make it a recurring event.'
  },

  // API-GENERATED CARDS (Only visible to QA Managers and Admins)
  {
    id: 'card-api-1',
    title: 'Romantic Dinner Cruise on the Bay',
    category: 'casualEats',
    description: 'Enjoy a romantic evening cruise with a three-course meal and stunning bay views.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400'],
    location: 'San Francisco Bay',
    venue: 'Bay Cruise Co.',
    price: '$120-180',
    priceRange: '$120-180',
    duration: '3 hours',
    rating: 0,
    reviews: 0,
    tags: ['Dinner Cruise', 'Romantic', 'Bay Views'],
    highlights: ['Three-course meal', 'Live music', 'Sunset views'],
    status: 'draft',
    createdBy: 'api-system',
    createdByRole: 'api',
    createdByName: 'AI System',
    isApiGenerated: true,
    createdAt: '2025-01-15T10:00:00Z',
    lastEdited: '2025-01-15T10:00:00Z'
  },
  {
    id: 'card-api-2',
    title: 'Hidden Speakeasy Cocktail Experience',
    category: 'sipChill',
    description: 'Discover a secret speakeasy with craft cocktails and 1920s ambiance.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400',
    images: ['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400'],
    location: 'North Beach',
    venue: 'Secret Door Lounge',
    price: '$40-60',
    priceRange: '$40-60',
    duration: '2 hours',
    rating: 0,
    reviews: 0,
    tags: ['Speakeasy', 'Cocktails', 'Hidden Gem'],
    highlights: ['Secret entrance', 'Craft cocktails', '1920s theme'],
    status: 'in-review',
    createdBy: 'api-system',
    createdByRole: 'api',
    createdByName: 'AI System',
    isApiGenerated: true,
    createdAt: '2025-01-16T14:00:00Z',
    lastEdited: '2025-01-16T14:00:00Z'
  },
  {
    id: 'card-api-3',
    title: 'Urban Photography Walking Tour',
    category: 'takeAStroll',
    description: 'Learn street photography while exploring SF\'s most photogenic neighborhoods.',
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400',
    images: ['https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400'],
    location: 'Mission District',
    venue: 'Street Photo SF',
    price: '$65-85',
    priceRange: '$65-85',
    duration: '3 hours',
    rating: 0,
    reviews: 0,
    tags: ['Photography', 'Walking Tour', 'Art'],
    highlights: ['Photography tips', 'Hidden murals', 'Small groups'],
    status: 'live',
    createdBy: 'api-system',
    createdByRole: 'api',
    createdByName: 'AI System',
    isApiGenerated: true,
    createdAt: '2025-01-17T09:00:00Z',
    lastEdited: '2025-01-17T09:00:00Z',
    publishedAt: '2025-01-18T08:00:00Z',
    views: 234,
    likes: 18,
    saves: 12,
    shares: 5
  }
];

/**
 * Get all live cards (what explorers see)
 */
export function getLiveCards(): PlatformCard[] {
  return PLATFORM_CARDS_SEED.filter(card => card.status === 'live');
}

/**
 * Get cards by creator
 */
export function getCardsByCreator(creatorId: string): PlatformCard[] {
  return PLATFORM_CARDS_SEED.filter(card => card.createdBy === creatorId);
}

/**
 * Get cards by business
 */
export function getCardsByBusiness(businessId: string): PlatformCard[] {
  return PLATFORM_CARDS_SEED.filter(card => card.businessId === businessId);
}

/**
 * Get cards by status
 */
export function getCardsByStatus(status: PlatformCard['status']): PlatformCard[] {
  return PLATFORM_CARDS_SEED.filter(card => card.status === status);
}

/**
 * Get cards by curator (for curator dashboard)
 */
export function getCardsByCurator(curatorId: string): PlatformCard[] {
  return PLATFORM_CARDS_SEED.filter(card => 
    card.createdBy === curatorId || card.curatorId === curatorId
  );
}
