/** #1615 stage-5 tester suite. FAILS-ON-REVERT: lowering the portrait boundary
 * to .38 fails VA1 independently of renderer structure and pixel assertions. */
import test from 'node:test'; import assert from 'node:assert/strict'; import path from 'node:path'; import { createRequire } from 'node:module'; import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const require=createRequire(import.meta.url);const C=require(path.join(ROOT,'packages/card-identity'));
const lin=(x)=>{const c=x/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4};const lum=(a)=>.2126*lin(a[0])+.7152*lin(a[1])+.0722*lin(a[2]);const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);const over=(f,a,b)=>f.map((x,i)=>x*a+b[i]*(1-a));const backdrop=(p,a)=>[p*(1-a),p*(1-a),p*(1-a)];
test('VA1 independent dense interstitial sweep reproduces published portrait boundaries',()=>{const s=C.SURFACES.s4Snippet,H=C.surfaceScrimHeight('s4Snippet'),a=C.rampAlphaAtDepth(C.plateTopDepth('s4Snippet'),H),u=C.plateUnderAlpha(a),edge=C.surfacePlateBoundary('s4Snippet');let pw=Infinity;for(let i=0;i<=25500;i++){const b=backdrop(i/100,a),p=over(C.PLATE.liftRgb,C.PLATE.liftAlpha,over(C.PLATE.underRgb,u,b)),e=over(edge.rgb,edge.alpha,b);pw=Math.min(pw,Math.max(ratio(p,b),ratio(e,b)))}const sw=C.SLIVER.offsets.map(offset=>{let w=Infinity,d=s.bottomInset+s.plateH+offset+s.sliver.height/2,sa=C.rampAlphaAtDepth(d,H);for(let i=0;i<=25500;i++){const b=backdrop(i/100,sa);w=Math.min(w,ratio(over([255,255,255],s.sliver.alpha,b),b))}return w});assert.ok(Math.abs(pw-3.3801)<.0001,pw);assert.ok(Math.abs(sw[0]-3.5033)<.0001,sw[0]);assert.ok(Math.abs(sw[1]-3.3484)<.0001,sw[1]);assert.ok(Math.min(pw,...sw)>=3)});
// [TEST-MOD-APPROVED #1615] Coverless S4/S5 was contrary to the binding
// no-synthetic-art contract. Exact versions remain immutable, but no eligible
// poster now fails closed before the renderer.
// [TEST-MOD-APPROVED #1615] Variant A changed the transport boundary to JPEG;
// the former literal `png` fixture was deliberately invalid and contradicted
// the new fail-closed contract, so this preserves VA2 with real JPEG bytes.
// [TEST-MOD-APPROVED #2589] This test pinned the exact hole #2589 exists to
// close: a coverless share was refused a card (404) and the renderer was
// asserted UNREACHABLE. The renderer now composes a card from the offering's own
// facts when there is no usable cover, so the coverless leg asserts the served
// card and its immutable headers instead. The two 404s that remain are the ones
// still genuinely unanswerable — a drifted version and an absent share — and
// both are asserted, so the change narrows this test rather than weakening it.
test('VA2 immutable image handler rejects drifted versions and absent shares, and serves the coverless fallback card',async()=>{const {createContentShareImageHandler}=require(path.join(ROOT,'mingla-business/api/content-share-image.js'));const covered={shortCode:'Aa0Bb1Cc2Dd3Ee4F',version:7,facts:{schemaVersion:1,kind:'brand',title:'Truthful'},media:{kind:'photo',url:'https://images.pexels.com/a.jpg',posterUrl:'https://images.pexels.com/a.jpg'}};const response=()=>({statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v},end(body){this.body=body}});const req=version=>({query:{code:covered.shortCode,version},headers:{'x-mingla-shared-card-proxy':'secret'}});const sharp=require(path.join(ROOT,'mingla-business/node_modules/sharp'));const jpeg=await sharp({create:{width:1080,height:1350,channels:3,background:'#0C0E12'}}).jpeg({quality:66,progressive:true}).toBuffer();process.env.SHARED_CARD_PROXY_SECRET='secret';const handler=createContentShareImageHandler(async(_code,version)=>({contentShare:version===7?covered:null}),async()=>jpeg);const stale=response();await handler(req('6'),stale);assert.equal(stale.statusCode,404);const exact=response();await handler(req('7'),exact);assert.equal(exact.statusCode,200);assert.ok(exact.body.equals(jpeg));assert.equal(exact.headers['content-type'],'image/jpeg');assert.equal(exact.headers['cache-control'],'public, max-age=31536000, immutable');const coverless=response();await createContentShareImageHandler(async()=>({contentShare:{...covered,media:null}}),async()=>jpeg)(req('7'),coverless);assert.equal(coverless.statusCode,200);assert.ok(coverless.body.equals(jpeg));assert.equal(coverless.headers['cache-control'],'public, max-age=31536000, immutable');const absent=response();await createContentShareImageHandler(async()=>({contentShare:null}),async()=>jpeg)(req('7'),absent);assert.equal(absent.statusCode,404)});
// [TEST-MOD-APPROVED #1615] Coverless HTML must omit image metadata and portrait
// markup; the old expectation falsely advertised an image that did not exist.
// [TEST-MOD-APPROVED #2589] `og:image` was asserted ABSENT for a coverless
// share, which is the defect: the page omitted the image block and the link
// shared as a bare URL. The tag is now always emitted and always truthful,
// because the image route always has a card to serve. Every assertion about
// what must NOT appear is kept and tightened — no legacy .png portrait URL, no
// video or GIF element, no fabricated media claim.
test('VA3 coverless HTML emits a truthful og:image and still never claims a photo',()=>{const {renderContentShareHtml}=require(path.join(ROOT,'mingla-business/server/socialPreview.js'));const html=renderContentShareHtml({shortCode:'Aa0Bb1Cc2Dd3Ee4F',version:1,facts:{schemaVersion:1,kind:'brand',title:'No cover'},media:null,destination:{}});const url='https://usemingla.com/og/s/Aa0Bb1Cc2Dd3Ee4F/v1-r2.jpg';assert.ok(html.includes(`<meta property="og:image" content="${url}" />`));assert.ok(html.includes(`<meta property="og:image:secure_url" content="${url}" />`));assert.ok(html.includes('<meta name="twitter:card" content="summary_large_image" />'));assert.doesNotMatch(html,/\/og\/s\/Aa0Bb1Cc2Dd3Ee4F\/v1\.png|<video|gif-motion|stock/)});
