/** #1615 stage-5 implementor suite. FAILS-ON-REVERT: removing the canonical
 * wordmark mount makes P2/P3 fail while receiver tests remain green. */
import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path';
import { createRequire } from 'node:module'; import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'); const require=createRequire(import.meta.url);
const CI=require(path.join(ROOT,'packages/card-identity')); const renderer=require(path.join(ROOT,'mingla-business/server/cardIdentityRenderer.js')); const preview=require(path.join(ROOT,'mingla-business/server/socialPreview.js'));
const cover='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const share=(kind,media=null)=>{const specific={place:{category:'Food',area:'Durham'},curated:{stopCount:3,area:'Durham'},event:{localDate:'Friday',venue:'Mingla Hall',status:'sold_out'},rsvp_event:{localDate:'Friday',venue:'Mingla Hall'},trip:{destination:'Durham',duration:'2 days'},experience:{area:'Durham',duration:'2 hours'},venue:{category:'Food',area:'Durham'},brand:{category:'Food',area:'Durham'}}[kind];return{shortCode:'Aa0Bb1Cc2Dd3Ee4F',version:7,facts:{schemaVersion:1,kind,title:`Canonical ${kind}`,...specific},media,destination:{}}};
test('P1 S4/S5 own one exact measured portrait descriptor',()=>{for(const key of ['s4Snippet','s5Og']){const s=CI.SURFACES[key];assert.deepEqual([s.w,s.h,s.sideInset,s.bottomInset,s.plateH,s.gap],[360,450,24,48,78,16]);assert.equal(CI.surfaceScrimHeight(key),322);assert.ok(Math.abs(CI.rampAlphaAtDepth(126,322)-.767283)<.000001);assert.equal(CI.surfacePlateUnder(key),.672);assert.equal(CI.surfacePlateBoundary(key).alpha,.42)}});
test('P2 runtime resolves and reads the canonical package SVG from the deployable workspace dependency',()=>{const resolved=require.resolve('@mingla/brand-assets/mingla-wordmark.svg',{paths:[path.join(ROOT,'mingla-business')]});assert.equal(fs.realpathSync(resolved),fs.realpathSync(path.join(ROOT,'packages/brand-assets/mingla-wordmark.svg')));const source=renderer.wordmarkSource();assert.match(source,/^data:image\/svg\+xml;base64,/);assert.ok(Buffer.from(source.split(',')[1],'base64').equals(fs.readFileSync(resolved)))});
// [TEST-MOD-APPROVED #1615] Coverless portrait generation was an incorrect
// assertion: S4/S5 require real eligible media and must never synthesize art.
// The covered path still proves the canonical wordmark and exact dimensions.
// [TEST-MOD-APPROVED #1615] Physical WhatsApp disproved the former PNG
// transport assertion; preserve the exact 4:5 design in a bounded JPEG.
test('P3 covered runtime renders the actual wordmark in an exact bounded JPEG portrait',async()=>{const jpeg=await renderer.renderContentSharePortraitJpeg(share('place',{kind:'photo',url:cover,posterUrl:cover}));const sharp=require(path.join(ROOT,'mingla-business/node_modules/sharp'));const metadata=await sharp(jpeg).metadata();assert.deepEqual([metadata.format,metadata.width,metadata.height],['jpeg',1080,1350]);assert.ok(jpeg.length<=renderer.MAX_CONTENT_SHARE_JPEG_BYTES);assert.deepEqual(Array.from(jpeg.subarray(0,2)),[0xff,0xd8]);assert.deepEqual(Array.from(jpeg.subarray(-2)),[0xff,0xd9])});
test('P4 all eight kinds build the same fixed portrait composition without fabricated copy',()=>{for(const kind of ['place','curated','event','rsvp_event','trip','experience','venue','brand'])assert.doesNotThrow(()=>renderer.contentSharePortraitElement(share(kind)));const source=fs.readFileSync(path.join(ROOT,'mingla-business/server/cardIdentityRenderer.js'),'utf8');assert.doesNotMatch(source,/Amazing experience|Date(?:s)? to be announced/)});
// [TEST-MOD-APPROVED #1615] The public content page previously duplicated an
// outer logo above the portrait; the portrait's measured logo pill is enough.
test('P6 S6 removes the redundant outer brand header without changing portrait identity',()=>{const html=preview.renderContentShareHtml(share('brand',{kind:'photo',url:cover,posterUrl:cover}));assert.doesNotMatch(html,/class="brand(?:\s|\")/);assert.doesNotMatch(html,/mingla-business-logo/);assert.doesNotMatch(html,/>Mingla Business</);assert.ok(renderer.wordmarkSource().startsWith('data:image/svg+xml;base64,'))});
// [TEST-MOD-APPROVED #1615] The old fixture used an arbitrary CDN host that
// the approved public-media policy must reject. Use the governed storage host
// and pin the independent play/sound controls added by the binding correction.
test('P5 S6 metadata, responsive portrait, terminal status, independent video controls and human hours are semantic',()=>{const event=share('event',{kind:'video',url:'https://gqnoajqerqhnvulmnyvv.supabase.co/storage/v1/object/public/share/a.mp4',posterUrl:'https://gqnoajqerqhnvulmnyvv.supabase.co/storage/v1/object/public/share/a.jpg'});const eventHtml=preview.renderContentShareHtml(event);for(const token of ['og:image:width\" content=\"1080','og:image:height\" content=\"1350','twitter:image:alt','aspect-ratio:4/5','max-width:1120px','playsinline','prefers-reduced-motion','saveData','IntersectionObserver','play-control','sound-control','Unmute video'])assert.ok(eventHtml.includes(token),token);assert.doesNotMatch(eventHtml,/>Buy tickets</);const venue=share('venue');venue.facts.hours=Array.from({length:7},(_,i)=>({day:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i],label:i===1?'Closed':'9 AM–5 PM',isToday:i===0}));const hoursHtml=preview.renderContentShareHtml(venue);assert.match(hoursHtml,/Monday/);assert.match(hoursHtml,/Closed/);assert.doesNotMatch(hoursHtml,/\{\"day\"/)});
