/** #1615 stage-6 tester suite. FAILS-ON-REVERT: bypassing single-flight cleanup
 * makes PA1 return version 1 twice instead of observing version 2. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),require=createRequire(import.meta.url),sharing=require(path.join(ROOT,'packages/sharing'));
test('PA1 single-flight coalesces concurrent work but re-reads sequentially for a new version',async()=>{const run=sharing.createContentShareSingleFlight();let calls=0,version=0;const load=async()=>{calls++;await Promise.resolve();return{version:++version}};const [a,b]=await Promise.all([run('same',load),run('same',load)]);assert.equal(calls,1);assert.equal(a.version,1);assert.equal(b.version,1);const c=await run('same',load);assert.equal(calls,2);assert.equal(c.version,2)});
test('PA2 hostile host and malformed percent encoding fail closed before identity creation',()=>{for(const bad of ['https://evil.test/e/a/b','https://host.usemingla.com/e/%E0%A4%A/b','not a url'])assert.equal(sharing.contentShareRequestFromPublicUrl(bad),null,bad)});
test('PA3 every platform intent carries the intelligent message exactly once',async()=>{const intents=await import(pathToFileURL(path.join(ROOT,'mingla-business/src/utils/shareIntents.ts')));const url='https://usemingla.com/s/Aa0Bb1Cc2Dd3Ee4F',message=`Bounded truth.\n\n${url}`;for(const value of [intents.twitterIntent(url,'Ignored',message),intents.whatsappIntent(url,'Ignored',message),intents.emailIntent(url,'Ignored',message),intents.smsIntent(url,'Ignored',message)]){const decoded=decodeURIComponent(value);assert.equal(decoded.split(url).length-1,1,value);assert.ok(decoded.includes('Bounded truth.'),value)}});
test('PA4 non-content invitations and file exports remain outside content adapter',()=>{for(const file of ['app-mobile/src/components/connections/AddFriendView.tsx','app-mobile/src/components/PairRequestModal.tsx','app-mobile/src/components/onboarding/OnboardingFriendsAndPairingStep.tsx','mingla-business/src/utils/guestCsvExport.ts']){assert.match(read(file),/Share\.share\(/,file);assert.doesNotMatch(read(file),/contentShareAdapter/,file)}});
test('PA5 raw or malformed hours never reach recipient-facing facts',async()=>{const mapper=await import(pathToFileURL(path.join(ROOT,'supabase/functions/_shared/contentShare.ts')));for(const bad of [{periods:[{}]},{weekdayDescriptions:['OpenNow: false']},[{weekday:0,open_time:{raw:true},close_time:'17:00'}]])assert.equal(mapper.normalizeServedHours(bad),undefined);const source=read('mingla-business/server/socialPreview.js');assert.doesNotMatch(source,/JSON\.stringify\(facts\.hours/)});
test('PA6 logged-out public RSVP event page sends the RSVP discriminator through both share mounts',()=>{const route=read('mingla-business/app/e/[brandSlug]/[eventSlug].tsx'),page=read('mingla-business/src/components/event/PublicEventPage.tsx');assert.match(route,/<PublicEventPage/);assert.doesNotMatch(route,/\buseAuth\b|\brequireAuth\b|router\.(?:replace|push)\([^)]*(?:login|sign-in)/i);assert.match(page,/const isRsvp = event\.event_type === "rsvp"/);assert.equal((page.match(/contentKind=\{isRsvp \? "rsvp_event" : "event"\}/g)||[]).length,2)});
