/** #1615 stage-6 implementor suite. FAILS-ON-REVERT: restoring the consumer
 * event Share.share call makes PH4 fail while the independent adapter tests pass. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),require=createRequire(import.meta.url),sharing=require(path.join(ROOT,'packages/sharing'));

test('PH1 route grammar covers six public business kinds and explicit RSVP',()=>{const cases=[['https://business.usemingla.com/e/a/b','event'],['https://business.usemingla.com/t/a/b','trip'],['https://business.usemingla.com/exp/a/b','experience'],['https://business.usemingla.com/b/a/v/b','venue'],['https://business.usemingla.com/b/a','brand']];for(const [url,kind] of cases)assert.equal(sharing.contentShareRequestFromPublicUrl(url).kind,kind);assert.equal(sharing.contentShareRequestFromPublicUrl(cases[0][0],'rsvp_event').kind,'rsvp_event')});
test('PH2 served hours become seven human rows and dates derive useful facts',async()=>{const mapper=await import(pathToFileURL(path.join(ROOT,'supabase/functions/_shared/contentShare.ts')));const descriptions=['Monday: 9 AM–5 PM','Tuesday: Closed','Wednesday: Open 24 hours','Thursday: 9 AM–5 PM','Friday: 9 AM–5 PM','Saturday: 10 AM–2 PM','Sunday: Closed'];const place=mapper.normalizeServedHours({weekdayDescriptions:descriptions});assert.equal(place.length,7);assert.deepEqual(place[1],{day:'Tuesday',label:'Closed'});const venue=mapper.normalizeServedHours(Array.from({length:7},(_,weekday)=>({weekday,open_time:'09:00',close_time:'17:00',is_closed:weekday===6})));assert.deepEqual(venue[0],{day:'Monday',label:'9 AM–5 PM'});assert.deepEqual(venue[6],{day:'Sunday',label:'Closed'});const trip=mapper.mapAuthoritativeShareFacts('trip',{row:{title:'Trip',slug:'trip',destination_text:'Durham',brands:{slug:'brand'}},date:{start_at:'2026-08-09T10:00:00Z'},dateRange:'Aug 9 – Aug 11',duration:'3 hours',tickets:[]});assert.equal(trip.facts.dateRange,'Aug 9 – Aug 11');assert.equal(trip.facts.duration,'3 hours')});
test('PH3 creation returns authoritative facts and selected served fields are present',()=>{assert.match(read('supabase/functions/_shared/contentShareService.ts'),/facts: mapped\.facts/);const mapper=read('supabase/functions/_shared/contentShare.ts');for(const field of ['opening_hours','hours,iana_timezone','dateRange:','duration: durationLabel'])assert.ok(mapper.includes(field),field);assert.match(mapper,/if \(countError\) throw/);assert.match(mapper,/upcomingCount: count \|\| 0/)});
test('PH4 every consumer content producer delegates to the one app adapter',()=>{for(const file of ['app-mobile/src/screens/Event/ConsumerEventDetailScreen.tsx','app-mobile/src/screens/Trip/ConsumerTripDetailScreen.tsx','app-mobile/src/screens/Experience/ConsumerExperienceDetailScreen.tsx','app-mobile/src/screens/ConsumerBrandProfileScreen.tsx','app-mobile/app/b/[brandSlug]/v/[venueSlug].tsx']){const source=read(file);assert.match(source,/shareContent\(/,file);assert.doesNotMatch(source,/Share\.share\(/,file)}const modal=read('app-mobile/src/components/ShareModal.tsx');assert.match(modal,/prepareContentShare\(/);assert.match(modal,/Clipboard\.setString\(prepared\.message\)/);
  // [TEST-MOD-APPROVED #1615] Written reason: regenerated messages now receive
  // the same sanitized planning preference as first creation; the old literal
  // incorrectly rejected that required third adapter argument.
  assert.match(modal,/messageForPreparedContentShare\(await sharedCardPromiseRef\.current, channel, \{ planningPreference: dateTimePreferences \}\)/)});
test('PH5 business event RSVP trip experience venue and brand share through its one adapter',()=>{const modal=read('mingla-business/src/components/ui/ShareModal.tsx');assert.match(modal,/prepareBusinessContentShare\(/);assert.match(modal,/prepared\.message/);assert.match(read('mingla-business/app/rsvp/[id]/index.tsx'),/contentKind="rsvp_event"/);for(const route of ['/e/','/t/','/exp/','/b/'])assert.ok(read('packages/sharing/index.js').includes(`parts[0] === '${route.split('/')[1]}'`),route)});
