import { Platform } from "react-native";
import { postHogService } from "../../services/postHogService";
import { captureWeb } from "../../analytics/webAnalytics";
export type PeopleEvent="people_page_viewed"|"people_book_opened"|"people_book_export_opened"|"people_book_search_used"|"people_add_opened"|"people_add_completed"|"people_add_review_required"|"people_import_selected"|"people_dependency_state_viewed"|"people_group_opened"|"people_legacy_audiences_redirected"|"people_conflict_queue_opened"|"people_conflict_resolved"|"people_conflict_resolve_failed"|"manual_group_create_started"|"manual_group_source_selected"|"manual_group_create_completed"|"manual_group_create_failed"|"manual_group_viewed"|"manual_group_search_used"|"manual_group_members_added"|"manual_group_members_removed"|"manual_group_renamed"|"manual_group_delete_blocked"|"manual_group_deleted"|"manual_group_import_completed"|"manual_group_conflicts_pending"|"manual_group_campaign_started"|"brand_person_merge_started"|"brand_person_merge_completed"|"brand_person_merge_blocked"|"brand_person_split_started"|"brand_person_split_completed"|"brand_person_split_escalated"|"brand_person_split_blocked"|"brand_person_primary_promoted"|"brand_person_primary_blocked";
export interface PeopleEventProperties {platform?:string;surface?:"page"|"book_sheet"|"detail"|"add_sheet"|"groups_sheet"|"conflict_sheet"|"merge_sheet"|"split_sheet";result?:"created"|"updated"|"unchanged"|"review"|"completed"|"blocked"|"escalated";dependency?:"import"|"export"|"reach"|"followers"|"extended";dependencyState?:"available"|"unavailable"|"flag_off";hasSearch?:boolean;bookSizeBucket?:"0"|"1_10"|"11_50"|"51_100"|"101_plus";groupKind?:string;errorCode?:string;candidateCountBucket?:"0"|"1"|"2_5"|"6_20"|"21_plus";contactCountBucket?:"0"|"1"|"2_5"|"6_plus";channel?:"email"|"phone";hadPriorSeparation?:boolean;hadOpenConflict?:boolean;durationBucket?:"under_1s"|"1_3s"|"3_10s"|"10s_plus";/* #2305 — `resolution`, `candidateCount` and `matchedOn` are the only way to learn
 * empirically whether operators separate more often on a single-channel match than on a
 * two-channel one, which answers SPEC 11-Q2 with data instead of intuition. `matchedOn`
 * carries the CHANNEL that matched, never the value that matched — no identity or
 * contact data enters analytics (#1774). */
resolution?:"merge"|"separate"|"dismiss";candidateCount?:number;matchedOn?:string;dismissedReason?:string;source?:"book_picker"|"import"|"empty"|"detail";groupId?:string;batchId?:string;countBucket?:"0"|"1_10"|"11_50"|"51_100"|"101_plus"}
export function capturePeople(event:PeopleEvent,properties:PeopleEventProperties={}):void{const safe={platform:Platform.OS,...properties};postHogService.capture(event,safe);if(Platform.OS==="web")captureWeb(event,safe);}
