import type { HostGuideKind, HostGuideRecord } from './shared'

export const HOST_GUIDE_FAMILY: Record<HostGuideKind, HostGuideRecord> = {
  event: {
    kind: 'event',
    eyebrow: 'Mingla Host · Event guide',
    title: 'Promote your event with one clear reason to go',
    subhead: 'Make the event easy to understand, send every channel to one action, then use a real forecast to pressure-test the plan.',
    tips: [
      { title: 'Lead with the reason to go.', detail: 'Name the audience, atmosphere and one thing they should not miss.' },
      { title: 'Keep the truth identical everywhere.', detail: 'Date, place, price and entry rules should match across every post and page.' },
      { title: 'Give people one next step.', detail: 'Ticket, RSVP or guest-list entry—not three competing actions.' },
    ],
    toolKey: 'event',
    toolLabel: 'Event Turnout Predictor',
    heroMedia: {
      src: '/marketing/host-icp/events-hall.jpg',
      alt: 'An event hall prepared for guests',
    },
    creationNoun: 'event',
    hostUrl: 'https://host.usemingla.com/event/create',
    hostAction: 'Create your event in Mingla Host',
    limitation: 'A forecast or audit is guidance, not a guarantee of reach, attendance, sales, price acceptance, or legal compliance.',
  },
  trip: {
    kind: 'trip',
    eyebrow: 'Mingla Host · Trip guide',
    title: 'Sell a trip people can picture and price',
    subhead: 'Show the complete journey, make the real cost understandable and give the traveller one clear way to join.',
    tips: [
      { title: 'Quote the full known trip.', detail: 'Include the stay, transport, activities and fees you genuinely know.' },
      { title: 'Make the boundaries obvious.', detail: 'Show inclusions, exclusions and payment timing before someone enquires.' },
      { title: 'Turn the itinerary into a story.', detail: 'Help people picture the pace and the moments they are paying for.' },
    ],
    toolKey: 'trip',
    toolLabel: 'Quote Any Trip',
    heroMedia: {
      src: '/marketing/host-icp/tours-trail.jpg',
      alt: 'Travellers walking together on an outdoor trail',
    },
    creationNoun: 'trip',
    hostUrl: 'https://host.usemingla.com/trip/create',
    hostAction: 'Create your trip in Mingla Host',
    limitation: 'A forecast or audit is guidance, not a guarantee of reach, attendance, sales, price acceptance, or legal compliance.',
  },
  venue: {
    kind: 'venue',
    eyebrow: 'Mingla Host · Venue guide',
    title: 'Make your venue easier to discover and choose',
    subhead: 'Show the real space clearly, answer the questions that slow a decision and make the next step obvious.',
    tips: [
      { title: 'Lead with complete real media.', detail: 'Show the room, entrance, layout and atmosphere people will actually find.' },
      { title: 'Explain how the space works.', detail: 'State capacity, setup options and location without vague superlatives.' },
      { title: 'Remove enquiry friction.', detail: 'Answer the questions that repeatedly delay a booking decision.' },
    ],
    toolKey: 'venue',
    toolLabel: 'Venue Website Grader',
    heroMedia: {
      src: '/marketing/host-icp/venues-space.jpg',
      alt: 'A venue arranged for a hosted gathering',
    },
    creationNoun: 'venue',
    hostUrl: 'https://host.usemingla.com/venue/create',
    hostAction: 'Add your venue to Mingla Host',
    limitation: 'A forecast or audit is guidance, not a guarantee of reach, attendance, sales, price acceptance, or legal compliance.',
  },
  experience: {
    kind: 'experience',
    eyebrow: 'Mingla Host · Experience guide',
    title: 'Package an experience people can picture and book',
    subhead: 'Make the outcome tangible, explain what is included and put one real price beside one clear action.',
    tips: [
      { title: 'Sell one clear result.', detail: 'Say what someone will make, learn, taste, see or feel.' },
      { title: 'Show the practical shape.', detail: 'State duration, inclusions and the group the experience fits.' },
      { title: 'Use one real price and action.', detail: 'Remove conflicting totals and competing ways to book.' },
    ],
    toolKey: 'experience',
    toolLabel: 'Undercharging Audit',
    heroMedia: {
      src: '/marketing/host-icp/creators-popup.jpg',
      alt: 'An independent host preparing a pop-up experience',
    },
    creationNoun: 'experience',
    hostUrl: 'https://host.usemingla.com/experience/create',
    hostAction: 'Create your experience in Mingla Host',
    limitation: 'A forecast or audit is guidance, not a guarantee of reach, attendance, sales, price acceptance, or legal compliance.',
  },
}
