/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'studio-users': StudioUserAuthOperations;
  };
  blocks: {};
  collections: {
    'studio-users': StudioUser;
    tenants: Tenant;
    pages: Page;
    media: Media;
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
    'publication-jobs': PublicationJob;
    'gateway-nonces': GatewayNonce;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'studio-users': StudioUsersSelect<false> | StudioUsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'publication-jobs': PublicationJobsSelect<false> | PublicationJobsSelect<true>;
    'gateway-nonces': GatewayNoncesSelect<false> | GatewayNoncesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: StudioUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StudioUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-users".
 */
export interface StudioUser {
  id: string;
  core_user_id?: string | null;
  tenants?:
    | {
        tenant?: (string | null) | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  collection: 'studio-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  core_site_id: string;
  core_brand_id: string;
  status: 'provisioning' | 'active' | 'suspended';
  renderer_key: string;
  renderer_version: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  tenant?: (string | null) | Tenant;
  role: 'home' | 'about' | 'menu' | 'gallery' | 'contact';
  slug: string;
  title: string;
  enabled?: boolean | null;
  nav_label: string;
  nav_order: number;
  revision: number;
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            media: string | Media;
            ctas?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich_text';
          }
        | {
            media: string | Media;
            alt: string;
            heading?: string | null;
            caption?: string | null;
            alignment: 'left' | 'right';
            id?: string | null;
            blockName?: string | null;
            blockType: 'media_feature';
          }
        | {
            heading: string;
            body?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            offering_ids: {
              offering_id: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'offering_grid';
          }
        | {
            heading: string;
            body?: string | null;
            reservation_target_id: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'venue_reservation';
          }
        | {
            heading?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'menu_link';
          }
        | {
            heading?: string | null;
            images: {
              media: string | Media;
              alt: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            address: string;
            map_url?: string | null;
            hours?:
              | {
                  day: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hours_location';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  name: string;
                  quote: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact_handoff';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
        | {
            size: 'small' | 'medium' | 'large';
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  state: 'UPLOADING' | 'QUARANTINED' | 'PROCESSING' | 'READY' | 'REJECTED' | 'RETRYABLE_FAILED' | 'TOMBSTONED';
  original_filename_safe: string;
  declared_mime: 'image/jpeg' | 'image/png' | 'image/webp';
  detected_mime?: string | null;
  bytes?: number | null;
  checksum?: string | null;
  quarantine_key?: string | null;
  approved_master_key?: string | null;
  rendition_manifest?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rejection_code?:
    | (
        | 'TYPE_NOT_ALLOWED'
        | 'TOO_LARGE'
        | 'DIMENSIONS_TOO_LARGE'
        | 'MIME_MISMATCH'
        | 'DECODE_FAILED'
        | 'CHECKSUM_MISMATCH'
        | 'METADATA_RETAINED'
        | 'PROCESSING_FAILED'
      )
    | null;
  created_by?: string | null;
  quarantine_delete_by?: string | null;
  recovery_until?: string | null;
  tombstoned_at?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  tenant?: (string | null) | Tenant;
  label?: string | null;
  pages?: (string | Page)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  tenant?: (string | null) | Tenant;
  label?: string | null;
  address?: string | null;
  hours_summary?: string | null;
  legal_text?: string | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  tenant?: (string | null) | Tenant;
  display_name: string;
  short_description?: string | null;
  logo?: (string | null) | Media;
  background_color?: string | null;
  foreground_color?: string | null;
  accent_color?: string | null;
  typography?: ('modern-sans' | 'editorial-serif') | null;
  canonical_url: string;
  seo_title?: string | null;
  seo_description?: string | null;
  social_image?: (string | null) | Media;
  analytics_consent_mode?: 'optional' | null;
  renderer_key?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-jobs".
 */
export interface PublicationJob {
  id: string;
  tenant?: (string | null) | Tenant;
  operation_id: string;
  source_revision_id: string;
  source_digest: string;
  validation_result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  artifact_key?: string | null;
  artifact_digest?: string | null;
  status: 'queued' | 'validating' | 'materializing' | 'probing' | 'published' | 'failed' | 'ambiguous';
  retry_count?: number | null;
  failure_code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-nonces".
 */
export interface GatewayNonce {
  id: string;
  nonce: string;
  direction: 'core_to_cms';
  site_id: string;
  operation_id: string;
  expires_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'studio-users';
        value: string | StudioUser;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'footer';
        value: string | Footer;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: string | SiteSetting;
      } | null)
    | ({
        relationTo: 'publication-jobs';
        value: string | PublicationJob;
      } | null)
    | ({
        relationTo: 'gateway-nonces';
        value: string | GatewayNonce;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'studio-users';
    value: string | StudioUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'studio-users';
    value: string | StudioUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-users_select".
 */
export interface StudioUsersSelect<T extends boolean = true> {
  core_user_id?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  core_site_id?: T;
  core_brand_id?: T;
  status?: T;
  renderer_key?: T;
  renderer_version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  role?: T;
  slug?: T;
  title?: T;
  enabled?: T;
  nav_label?: T;
  nav_order?: T;
  revision?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              media?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        rich_text?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        media_feature?:
          | T
          | {
              media?: T;
              alt?: T;
              heading?: T;
              caption?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        offering_grid?:
          | T
          | {
              heading?: T;
              offering_ids?:
                | T
                | {
                    offering_id?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        venue_reservation?:
          | T
          | {
              heading?: T;
              body?: T;
              reservation_target_id?: T;
              id?: T;
              blockName?: T;
            };
        menu_link?:
          | T
          | {
              heading?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hours_location?:
          | T
          | {
              heading?: T;
              address?: T;
              map_url?: T;
              hours?:
                | T
                | {
                    day?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    name?: T;
                    quote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact_handoff?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  state?: T;
  original_filename_safe?: T;
  declared_mime?: T;
  detected_mime?: T;
  bytes?: T;
  checksum?: T;
  quarantine_key?: T;
  approved_master_key?: T;
  rendition_manifest?: T;
  rejection_code?: T;
  created_by?: T;
  quarantine_delete_by?: T;
  recovery_until?: T;
  tombstoned_at?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  pages?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  address?: T;
  hours_summary?: T;
  legal_text?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  display_name?: T;
  short_description?: T;
  logo?: T;
  background_color?: T;
  foreground_color?: T;
  accent_color?: T;
  typography?: T;
  canonical_url?: T;
  seo_title?: T;
  seo_description?: T;
  social_image?: T;
  analytics_consent_mode?: T;
  renderer_key?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-jobs_select".
 */
export interface PublicationJobsSelect<T extends boolean = true> {
  tenant?: T;
  operation_id?: T;
  source_revision_id?: T;
  source_digest?: T;
  validation_result?: T;
  artifact_key?: T;
  artifact_digest?: T;
  status?: T;
  retry_count?: T;
  failure_code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-nonces_select".
 */
export interface GatewayNoncesSelect<T extends boolean = true> {
  nonce?: T;
  direction?: T;
  site_id?: T;
  operation_id?: T;
  expires_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}