import type { ServerNotification } from '../../../hooks/useNotifications';

const baseFields = (id: string, type: string, isRead: boolean, createdAt: string) => ({
  id,
  user_id: 'recipient-uuid',
  type,
  is_read: isRead,
  read_at: isRead ? createdAt : null,
  push_sent: true,
  created_at: createdAt,
  expires_at: null,
  related_type: null,
  related_id: null,
});

export const MOCK_NOTIFICATIONS: ServerNotification[] = [
  {
    ...baseFields('n-collab-invite', 'collaboration_invite_received', false, '2026-05-24T18:00:00Z'),
    title: 'Marcus Rivera invited you to plan',
    body: 'Join "Brunch Plans" and start swiping together.',
    actor_id: 'actor-marcus',
    related_id: 'invite-123',
    related_type: 'collaboration_invite',
    data: {
      deepLink: 'mingla://session/sess-123',
      type: 'collaboration_invite_received',
      sessionId: 'sess-123',
      sessionName: 'Brunch Plans',
      inviteId: 'invite-123',
      inviterId: 'actor-marcus',
      inviterName: 'Marcus Rivera',
      inviterAvatarUrl: 'https://avatars.example.com/marcus.jpg',
    },
  },
  {
    ...baseFields('n-friend-req', 'friend_request_received', false, '2026-05-24T17:30:00Z'),
    title: 'Sarah Chen wants to connect',
    body: 'Tap to accept or pass.',
    actor_id: 'actor-sarah',
    related_id: 'fr-456',
    related_type: 'friend_request',
    data: {
      deepLink: 'mingla://connections?tab=requests',
      type: 'friend_request',
      requestId: 'fr-456',
      senderId: 'actor-sarah',
      senderUsername: 'sarahc',
    },
  },
  {
    ...baseFields('n-pair-visit', 'paired_user_visited', false, '2026-05-24T16:00:00Z'),
    title: 'Marcus visited a place',
    body: 'Marcus visited Kashin Japanese Restaurant',
    actor_id: 'actor-marcus',
    related_id: 'visit-789',
    related_type: 'visit',
    data: { deepLink: 'mingla://discover?paired=true' },
  },
  {
    ...baseFields('n-dm', 'direct_message_received', true, '2026-05-23T20:00:00Z'),
    title: 'Sarah Chen',
    body: 'Hey! Are you free Friday?',
    actor_id: 'actor-sarah',
    related_id: 'conv-abc',
    related_type: 'conversation',
    data: { deepLink: 'mingla://chat/conv-abc?type=direct' },
  },
  {
    ...baseFields('n-cal-tomorrow', 'calendar_reminder_tomorrow', false, '2026-05-23T08:00:00Z'),
    title: 'Tomorrow: Date Night Brunch',
    body: "Don't forget - Date Night Brunch is tomorrow at 11 AM.",
    actor_id: null,
    related_id: 'cal-101',
    related_type: 'calendar_entry',
    data: { deepLink: 'mingla://calendar/cal-101' },
  },
  {
    ...baseFields('n-feedback', 'visit_feedback_prompt', true, '2026-05-22T19:00:00Z'),
    title: 'How was Date Night Brunch?',
    body: 'Leave a quick review - it helps your future recommendations.',
    actor_id: null,
    related_id: 'exp-202',
    related_type: 'experience',
    data: { deepLink: 'mingla://review/exp-202' },
  },
  {
    ...baseFields('n-digest', 'weekly_digest', true, '2026-05-20T09:00:00Z'),
    title: 'Your week on Mingla',
    body: 'You saved 12 places, planned 3 outings, and connected with 2 new friends.',
    actor_id: null,
    related_id: null,
    related_type: null,
    data: { deepLink: 'mingla://home' },
  },
  {
    ...baseFields('n-referral', 'referral_credited', true, '2026-05-19T14:00:00Z'),
    title: 'You earned a free month!',
    body: 'Marcus joined Mingla from your invite.',
    actor_id: null,
    related_id: null,
    related_type: null,
    data: { deepLink: 'mingla://profile?tab=subscription' },
  },
];
