export const HOST_FIXTURE_IDS = {
  event: "sample-live-event-3176",
  brand: "sample-host-brand-3176",
  ticket: "sample-free-pass-3176",
} as const;

export const sampleBrand = {
  id: HOST_FIXTURE_IDS.brand,
  displayName: "Sample City Sessions",
  slug: "sample-city-sessions",
  address: "Sample Arts District",
  coverHue: 25,
  role: "owner",
  stats: { events: 1, followers: 0, rev: 0, rev7d: 0, attendees: 0 },
  currentLiveEvent: null,
  defaultCurrency: "USD",
  theme: null,
};

export const sampleLiveEvent = {
  id: HOST_FIXTURE_IDS.event,
  serverEventId: null,
  brandId: HOST_FIXTURE_IDS.brand,
  brandSlug: sampleBrand.slug,
  eventSlug: "sample-rooftop-listening-session",
  status: "scheduled",
  publishedAt: "2026-09-10T18:00:00.000Z",
  cancelledAt: null,
  endedAt: null,
  event_type: "event",
  name: "Sample rooftop listening session",
  description: "A small sunset session with a clear schedule and a free sample pass.",
  format: "in-person",
  category: null,
  partyTypes: ["listening-party"],
  vibeTags: ["relaxed"],
  musicGenres: ["soul"],
  city: "Sample City",
  locationGeo: null,
  cityGeo: null,
  whenMode: "single",
  date: "2026-10-17",
  doorsOpen: "19:00",
  endsAt: "22:00",
  masterStartAtUtc: "2026-10-17T23:00:00.000Z",
  masterEndAtUtc: "2026-10-18T02:00:00.000Z",
  timezone: "America/New_York",
  recurrenceRule: null,
  multiDates: [],
  venueName: "Sample Rooftop",
  address: "Sample Arts District",
  onlineUrl: null,
  hideAddressUntilTicket: false,
  coverHue: 25,
  coverMediaUrl: null,
  coverMediaType: null,
  coverGallery: [],
  currency: "USD",
  themeOverrides: null,
  tickets: [{ id: HOST_FIXTURE_IDS.ticket, name: "Sample guest pass", description: "Free entry for this sample listing.", priceGbp: 0, priceAllInGbp: 0, currency: "USD", isFree: true, isUnlimited: true, capacity: null, visibility: "visible", passwordProtected: false, password: null, saleStartAt: null, saleEndAt: null, approvalRequired: false, waitlistEnabled: false, availableAt: "online", displayOrder: 0 }],
  visibility: "public",
  requireApproval: false,
  allowTransfers: false,
  hideRemainingCount: false,
  passwordProtected: false,
  privateGuestList: false,
  inPersonPaymentsEnabled: false,
  orders: [],
  createdAt: "2026-09-10T18:00:00.000Z",
  updatedAt: "2026-09-10T18:00:00.000Z",
};
