import React, { useState, useEffect, useRef } from "react";
import {
  Text,
  View,
  TouchableOpacity,
  StyleSheet,
  StatusBar,
  ActivityIndicator,
  Alert,
  ScrollView,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Input } from "../ui/input";
import {
  generateUsernameFromName,
  generateUniqueUsername,
  checkUsernameAvailability,
  sanitizeUsername,
} from "../../utils/usernameUtils";

interface SignUpFormProps {
  onSignUp: (userData: {
    email: string;
    password: string;
    name: string;
    username: string;
  }) => void;
  onSwitchToSignIn: () => void;
  onBack: () => void;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  scrollContent: {
    flexGrow: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "transparent",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  minglaText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#eb7825",
    letterSpacing: 0.3,
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  formWrapper: {
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
  },
  formHeader: {
    marginBottom: 48,
    paddingHorizontal: 4,
  },
  formTitle: {
    fontSize: 36,
    fontWeight: "800",
    color: "#0a0a0a",
    marginBottom: 12,
    letterSpacing: -1,
    lineHeight: 44,
  },
  formSubtitle: {
    fontSize: 16,
    color: "#64748b",
    lineHeight: 24,
  },
  inputContainer: {
    marginBottom: 28,
  },
  inputLabel: {
    color: "#0f172a",
    fontWeight: "600",
    fontSize: 14,
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  inputWrapper: {
    position: "relative",
    width: "100%",
  },
  inputIcon: {
    position: "absolute",
    left: 16,
    top: 15,
    zIndex: 1,
    pointerEvents: "none",
  },
  passwordToggle: {
    position: "absolute",
    right: 12,
    top: 13,
    padding: 8,
    zIndex: 1,
    borderRadius: 8,
  },
  submitButton: {
    width: "100%",
    backgroundColor: "#eb7825",
    paddingVertical: 18,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  submitButtonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  submitButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  alternativeAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 32,
    paddingVertical: 12,
  },
  alternativeText: {
    color: "#64748b",
    fontSize: 15,
    fontWeight: "500",
  },
  alternativeLink: {
    color: "#eb7825",
    fontWeight: "700",
    fontSize: 15,
    marginLeft: 6,
  },
  usernameLabelContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  generateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#fff7ed",
  },
  generateButtonText: {
    color: "#eb7825",
    fontSize: 13,
    fontWeight: "600",
  },
  usernameStatusIcon: {
    position: "absolute",
    right: 12,
    top: 14,
    padding: 4,
    zIndex: 1,
  },
  usernameHint: {
    fontSize: 12,
    color: "#10b981",
    marginTop: 8,
    marginLeft: 4,
    fontWeight: "500",
  },
  usernameHintError: {
    color: "#ef4444",
  },
  usernameAutoGeneratedHint: {
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 6,
    marginLeft: 4,
  },
});

export default function SignUpForm({
  onSignUp,
  onSwitchToSignIn,
  onBack,
}: SignUpFormProps) {
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState({
    email: "",
    password: "",
    name: "",
    username: "",
  });
  const [usernameStatus, setUsernameStatus] = useState<{
    checking: boolean;
    available: boolean | null;
    isAutoGenerated: boolean;
  }>({
    checking: false,
    available: null,
    isAutoGenerated: true,
  });

  const nameDebounceRef = useRef<NodeJS.Timeout | null>(null);
  const usernameCheckDebounceRef = useRef<NodeJS.Timeout | null>(null);

  // Auto-generate username when name changes
  useEffect(() => {
    if (nameDebounceRef.current) {
      clearTimeout(nameDebounceRef.current);
    }

    if (formData.name.trim().length > 0) {
      nameDebounceRef.current = setTimeout(async () => {
        setUsernameStatus((prev) => {
          if (prev.isAutoGenerated) {
            generateUniqueUsername(formData.name).then((generatedUsername) => {
              setFormData((prev) => ({ ...prev, username: generatedUsername }));
              setUsernameStatus({
                checking: true,
                available: null,
                isAutoGenerated: true,
              });
              checkUsernameAvailability(generatedUsername).then(
                (isAvailable) => {
                  setUsernameStatus({
                    checking: false,
                    available: isAvailable,
                    isAutoGenerated: true,
                  });
                }
              );
            });
          }
          return prev;
        });
      }, 500);
    }

    return () => {
      if (nameDebounceRef.current) {
        clearTimeout(nameDebounceRef.current);
      }
    };
  }, [formData.name]);

  // Check username availability when username changes
  useEffect(() => {
    if (usernameCheckDebounceRef.current) {
      clearTimeout(usernameCheckDebounceRef.current);
    }

    if (formData.username.trim().length === 0) {
      setUsernameStatus((prev) => ({
        ...prev,
        checking: false,
        available: null,
      }));
      return;
    }

    const sanitized = sanitizeUsername(formData.username);
    if (sanitized.length < 3) {
      setUsernameStatus((prev) => ({
        ...prev,
        checking: false,
        available: null, // Set to null to show "too short" message instead of "taken"
      }));
      return;
    }

    setUsernameStatus((prev) => ({
      ...prev,
      checking: true,
    }));

    usernameCheckDebounceRef.current = setTimeout(async () => {
      const isAvailable = await checkUsernameAvailability(sanitized);
      setUsernameStatus((prev) => ({
        checking: false,
        available: isAvailable,
        isAutoGenerated: prev.isAutoGenerated,
      }));
    }, 500);

    return () => {
      if (usernameCheckDebounceRef.current) {
        clearTimeout(usernameCheckDebounceRef.current);
      }
    };
  }, [formData.username]);

  const handleInputChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (field === "username") {
      setUsernameStatus((prev) => ({ ...prev, isAutoGenerated: false }));
    }
  };

  const handleGenerateNewUsername = async () => {
    if (formData.name.trim().length === 0) {
      Alert.alert(
        "Name Required",
        "Please enter your name first to generate a username."
      );
      return;
    }

    setUsernameStatus({
      checking: true,
      available: null,
      isAutoGenerated: true,
    });

    const newUsername = await generateUniqueUsername(formData.name);
    setFormData((prev) => ({ ...prev, username: newUsername }));

    const isAvailable = await checkUsernameAvailability(newUsername);
    setUsernameStatus({
      checking: false,
      available: isAvailable,
      isAutoGenerated: true,
    });
  };

  const handleSubmit = async () => {
    if (!formData.name.trim()) {
      Alert.alert("Validation Error", "Please enter your full name.");
      return;
    }

    if (!formData.email.trim()) {
      Alert.alert("Validation Error", "Please enter your email address.");
      return;
    }

    if (!formData.password.trim() || formData.password.length < 6) {
      Alert.alert(
        "Validation Error",
        "Password must be at least 6 characters long."
      );
      return;
    }

    const sanitizedUsername = sanitizeUsername(formData.username);
    if (sanitizedUsername.length < 3) {
      Alert.alert(
        "Validation Error",
        "Username must be at least 3 characters long and contain only letters, numbers, and underscores."
      );
      return;
    }

    if (usernameStatus.checking) {
      Alert.alert("Please Wait", "Checking username availability...");
      return;
    }

    if (usernameStatus.available === false) {
      Alert.alert(
        "Username Taken",
        "This username is already taken. Please choose another one."
      );
      return;
    }

    const isAvailable = await checkUsernameAvailability(sanitizedUsername);
    if (!isAvailable) {
      Alert.alert(
        "Username Taken",
        "This username is already taken. Please choose another one."
      );
      setUsernameStatus({
        checking: false,
        available: false,
        isAutoGenerated: usernameStatus.isAutoGenerated,
      });
      return;
    }

    setIsLoading(true);
    try {
      const result = onSignUp({
        email: formData.email.trim(),
        password: formData.password,
        name: formData.name.trim(),
        username: sanitizedUsername,
      });
    } catch (error) {
      console.error("Sign up error:", error);
      const errorMessage =
        error instanceof Error
          ? error.message
          : typeof error === "string"
          ? error
          : error?.toString?.() ||
            "An error occurred during sign up. Please try again.";

      Alert.alert(
        "Sign Up Failed",
        errorMessage,
        [{ text: "OK", style: "default" }],
        { cancelable: true }
      );
    } finally {
      setTimeout(() => {
        setIsLoading(false);
      }, 500);
    }
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#ffffff" />

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={onBack} style={styles.backButton}>
            <Ionicons name="arrow-back" size={22} color="#475569" />
          </TouchableOpacity>
          <View style={styles.headerCenter}>
            <Text style={styles.minglaText}>Mingla</Text>
          </View>
          <View style={{ width: 40 }} />
        </View>

        {/* Form Content */}
        <View style={styles.formContainer}>
          <View style={styles.formWrapper}>
            {/* Form Header */}
            <View style={styles.formHeader}>
              <Text style={styles.formTitle}>Create Account</Text>
              <Text style={styles.formSubtitle}>
                Start discovering amazing experiences today
              </Text>
            </View>

            {/* Name field */}
            <View style={styles.inputContainer}>
              <Text style={styles.inputLabel}>Full Name</Text>
              <View style={styles.inputWrapper}>
                <Ionicons
                  name="person-outline"
                  size={20}
                  color="#94a3b8"
                  style={styles.inputIcon}
                />
                <Input
                  type="text"
                  value={formData.name}
                  onChangeText={(value) => handleInputChange("name", value)}
                  placeholder="John Doe"
                  placeholderTextColor="#cbd5e1"
                  required
                  style={{
                    backgroundColor: "#f8fafc",
                    borderWidth: 0,
                    borderRadius: 12,
                    paddingHorizontal: 16,
                    paddingLeft: 48,
                    fontSize: 16,
                    color: "#0f172a",
                    height: 54,
                    fontWeight: "500",
                  }}
                />
              </View>
            </View>

            {/* Username field */}
            <View style={styles.inputContainer}>
              <View style={styles.usernameLabelContainer}>
                <Text style={styles.inputLabel}>Username</Text>
                {usernameStatus.isAutoGenerated && formData.username && (
                  <TouchableOpacity
                    onPress={handleGenerateNewUsername}
                    style={styles.generateButton}
                  >
                    <Ionicons name="refresh" size={14} color="#eb7825" />
                    <Text style={styles.generateButtonText}>New</Text>
                  </TouchableOpacity>
                )}
              </View>
              <View style={styles.inputWrapper}>
                <Ionicons
                  name="at"
                  size={20}
                  color="#94a3b8"
                  style={styles.inputIcon}
                />
                <Input
                  type="text"
                  value={formData.username}
                  onChangeText={(value) => {
                    const sanitized = value
                      .toLowerCase()
                      .replace(/[^a-z0-9_]/g, "");
                    handleInputChange("username", sanitized);
                  }}
                  placeholder="johndoe"
                  placeholderTextColor="#cbd5e1"
                  autoCapitalize="none"
                  style={{
                    backgroundColor: "#f8fafc",
                    borderRadius: 12,
                    paddingHorizontal: 16,
                    paddingLeft: 48,
                    paddingRight:
                      usernameStatus.checking ||
                      usernameStatus.available !== null
                        ? 48
                        : 16,
                    fontSize: 16,
                    color: "#0f172a",
                    height: 54,
                    fontWeight: "500",
                    borderColor:
                      usernameStatus.available === false
                        ? "#f87171"
                        : usernameStatus.available === true
                        ? "#34d399"
                        : "transparent",
                    borderWidth: usernameStatus.available !== null ? 2 : 0,
                  }}
                />
                {usernameStatus.checking && (
                  <View style={styles.usernameStatusIcon}>
                    <ActivityIndicator size="small" color="#64748b" />
                  </View>
                )}
                {!usernameStatus.checking &&
                  usernameStatus.available === true && (
                    <View style={styles.usernameStatusIcon}>
                      <Ionicons
                        name="checkmark-circle"
                        size={22}
                        color="#10b981"
                      />
                    </View>
                  )}
                {!usernameStatus.checking &&
                  usernameStatus.available === false && (
                    <TouchableOpacity
                      style={styles.usernameStatusIcon}
                      onPress={() => {
                        setFormData((prev) => ({ ...prev, username: "" }));
                        setUsernameStatus({
                          checking: false,
                          available: null,
                          isAutoGenerated: false,
                        });
                      }}
                      activeOpacity={0.7}
                    >
                      <Ionicons name="close-circle" size={22} color="#ef4444" />
                    </TouchableOpacity>
                  )}
              </View>
              {!usernameStatus.checking &&
                formData.username &&
                (() => {
                  const sanitized = sanitizeUsername(formData.username);
                  const isTooShort = sanitized.length < 3;

                  if (isTooShort) {
                    return (
                      <Text
                        style={[styles.usernameHint, styles.usernameHintError]}
                      >
                        Username must be at least 3 characters
                      </Text>
                    );
                  }

                  if (usernameStatus.available === true) {
                    return (
                      <Text style={styles.usernameHint}>
                        Username available
                      </Text>
                    );
                  }

                  if (usernameStatus.available === false) {
                    return (
                      <Text
                        style={[styles.usernameHint, styles.usernameHintError]}
                      >
                        Username already taken
                      </Text>
                    );
                  }

                  return null;
                })()}
              {usernameStatus.isAutoGenerated && formData.username && (
                <Text style={styles.usernameAutoGeneratedHint}>
                  Auto-generated from your name
                </Text>
              )}
            </View>

            {/* Email field */}
            <View style={styles.inputContainer}>
              <Text style={styles.inputLabel}>Email</Text>
              <View style={styles.inputWrapper}>
                <Ionicons
                  name="mail-outline"
                  size={20}
                  color="#94a3b8"
                  style={styles.inputIcon}
                />
                <Input
                  type="email"
                  value={formData.email}
                  onChangeText={(value) => handleInputChange("email", value)}
                  placeholder="john@example.com"
                  placeholderTextColor="#cbd5e1"
                  required
                  style={{
                    backgroundColor: "#f8fafc",
                    borderWidth: 0,
                    borderRadius: 12,
                    paddingHorizontal: 16,
                    paddingLeft: 48,
                    fontSize: 16,
                    color: "#0f172a",
                    height: 54,
                    fontWeight: "500",
                  }}
                />
              </View>
            </View>

            {/* Password field */}
            <View style={styles.inputContainer}>
              <Text style={styles.inputLabel}>Password</Text>
              <View style={styles.inputWrapper}>
                <Ionicons
                  name="lock-closed-outline"
                  size={20}
                  color="#94a3b8"
                  style={styles.inputIcon}
                />
                <Input
                  type={showPassword ? "text" : "password"}
                  value={formData.password}
                  onChangeText={(value) => handleInputChange("password", value)}
                  placeholder="••••••••"
                  placeholderTextColor="#cbd5e1"
                  required
                  style={{
                    backgroundColor: "#f8fafc",
                    borderWidth: 0,
                    borderRadius: 12,
                    paddingHorizontal: 16,
                    paddingLeft: 48,
                    paddingRight: 48,
                    fontSize: 16,
                    color: "#0f172a",
                    height: 54,
                    fontWeight: "500",
                  }}
                />
                <TouchableOpacity
                  onPress={() => setShowPassword(!showPassword)}
                  style={styles.passwordToggle}
                >
                  {showPassword ? (
                    <Ionicons name="eye-off" size={20} color="#64748b" />
                  ) : (
                    <Ionicons name="eye" size={20} color="#64748b" />
                  )}
                </TouchableOpacity>
              </View>
            </View>

            {/* Submit Button */}
            <TouchableOpacity
              onPress={handleSubmit}
              style={styles.submitButton}
              activeOpacity={0.8}
              disabled={isLoading}
            >
              <View style={styles.submitButtonContent}>
                {isLoading && <ActivityIndicator size="small" color="white" />}
                <Text style={styles.submitButtonText}>Create Account</Text>
              </View>
            </TouchableOpacity>

            {/* Alternative Action */}
            <View style={styles.alternativeAction}>
              <Text style={styles.alternativeText}>
                Already have an account?{" "}
              </Text>
              <TouchableOpacity onPress={onSwitchToSignIn}>
                <Text style={styles.alternativeLink}>Sign In</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}
