/**
 * /hub/experiences (ORCH-0826) — Hub > Experiences sub-route.
 *
 * Empty-state placeholder for M0. Single-intent experiences ship in Ve5+
 * (menu AI parser → Restaurant experiences, activities AI → Play, schedule
 * AI → Creative & Arts) when physical-venue claim is complete.
 *
 * Per Q7 SPEC: short and friendly copy.
 *
 * Mingla_Artifacts/specs/SPEC_ORCH-0826_M0_HUB_FOUNDATION.md §6.8
 */

import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import {
  glass,
  radius,
  spacing,
  text as textTokens,
  typography,
} from "../../../src/constants/designSystem";

export default function HubExperiencesRoute(): React.ReactElement {
  return (
    <ScrollView contentContainerStyle={styles.scrollContent}>
      <View style={styles.placeholderCard}>
        <Text style={styles.title}>Experiences coming soon.</Text>
        <Text style={styles.body}>
          Single-intent experiences for verified venue brands — like
          &ldquo;Bottomless brunch Saturdays&rdquo; or &ldquo;Date-night
          tasting menu.&rdquo; Generated by AI from your menu and curated
          by you. Ships in a few weeks.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scrollContent: {
    padding: spacing.md,
    paddingBottom: 120,
  },
  placeholderCard: {
    padding: spacing.xl,
    backgroundColor: glass.tint.profileBase,
    borderColor: glass.border.profileBase,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radius.xl,
    gap: spacing.md,
  },
  title: {
    fontSize: typography.h3.fontSize,
    lineHeight: typography.h3.lineHeight,
    fontWeight: typography.h3.fontWeight,
    color: textTokens.primary,
  },
  body: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    color: textTokens.secondary,
  },
});
