-- Migration: 20260312400001_fix_collaboration_session_bugs.sql
-- Description: Fixes critical collaboration session bugs identified in forensic investigation.
--   C2: Phone invite trigger now also converts pending_session_invites
--   H1: Unique constraint on collaboration_sessions.board_id prevents race condition
--   H10: Wider UNIQUE on pending_session_invites to allow multiple inviters per phone
--   M4: Add price_tiers column to board_session_preferences if missing

-- ═══════════════════════════════════════════════════════════
-- C2: Rewrite phone invite trigger to ALSO convert pending_session_invites
-- When a non-app user signs up and verifies their phone, we must:
--   1. Convert pending_invites (friend invites) — already done
--   2. Convert pending_session_invites — NEW: create collaboration_invites rows
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.convert_pending_invites_on_phone_verified()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  pending RECORD;
  session_pending RECORD;
  new_invite_id UUID;
BEGIN
  -- Only fire when phone changes from NULL to a value (or changes to a new value)
  IF NEW.phone IS NULL OR (OLD.phone IS NOT NULL AND OLD.phone = NEW.phone) THEN
    RETURN NEW;
  END IF;

  -- ── PART 1: Convert pending friend invites (existing logic, unchanged) ──
  FOR pending IN
    SELECT * FROM public.pending_invites
    WHERE phone_e164 = NEW.phone
      AND status = 'pending'
      AND inviter_id != NEW.id   -- prevent self-conversion
  LOOP
    -- 1. Create legacy friend_requests as PENDING
    INSERT INTO public.friend_requests (sender_id, receiver_id, status)
    VALUES (pending.inviter_id, NEW.id, 'pending')
    ON CONFLICT (sender_id, receiver_id) DO NOTHING;

    -- 2. Create friend_links as PENDING
    INSERT INTO public.friend_links (
      requester_id, target_id, status
    )
    VALUES (
      pending.inviter_id, NEW.id, 'pending'
    )
    ON CONFLICT DO NOTHING;

    -- 3. Mark pending_invite as converted
    UPDATE public.pending_invites
    SET status = 'converted', converted_user_id = NEW.id, converted_at = NOW()
    WHERE id = pending.id;

    -- 4. Referral credit
    INSERT INTO public.referral_credits (referrer_id, referred_id, pending_invite_id, status)
    VALUES (pending.inviter_id, NEW.id, pending.id, 'pending')
    ON CONFLICT (referrer_id, referred_id) DO NOTHING;
  END LOOP;

  -- ── PART 2: Convert pending SESSION invites (NEW — fixes C2) ──
  FOR session_pending IN
    SELECT * FROM public.pending_session_invites
    WHERE phone_e164 = NEW.phone
      AND status = 'pending'
      AND inviter_id != NEW.id   -- prevent self-conversion
  LOOP
    -- 1. Create a real collaboration_invite for the now-verified user
    INSERT INTO public.collaboration_invites (
      session_id, inviter_id, invitee_id, status
    )
    VALUES (
      session_pending.session_id,
      session_pending.inviter_id,
      NEW.id,
      'pending'
    )
    ON CONFLICT DO NOTHING
    RETURNING id INTO new_invite_id;

    -- 2. Add the user as a session participant (not yet accepted)
    IF new_invite_id IS NOT NULL THEN
      INSERT INTO public.session_participants (
        session_id, user_id, has_accepted
      )
      VALUES (
        session_pending.session_id, NEW.id, false
      )
      ON CONFLICT (session_id, user_id) DO NOTHING;
    END IF;

    -- 3. Mark the pending session invite as converted
    UPDATE public.pending_session_invites
    SET status = 'converted',
        converted_invite_id = COALESCE(new_invite_id, converted_invite_id),
        updated_at = NOW()
    WHERE id = session_pending.id;
  END LOOP;

  RETURN NEW;
END;
$$;

-- Re-attach trigger (idempotent)
DROP TRIGGER IF EXISTS trg_convert_pending_invites_on_phone ON public.profiles;
CREATE TRIGGER trg_convert_pending_invites_on_phone
  AFTER UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.convert_pending_invites_on_phone_verified();


-- ═══════════════════════════════════════════════════════════
-- H10: Fix UNIQUE constraint on pending_session_invites
-- Old: UNIQUE(session_id, phone_e164) — blocks multiple inviters for same phone+session
-- New: UNIQUE(session_id, inviter_id, phone_e164) — each inviter can invite a phone once per session
-- ═══════════════════════════════════════════════════════════

-- Drop the old constraint (name auto-generated by CREATE TABLE ... UNIQUE)
ALTER TABLE public.pending_session_invites
  DROP CONSTRAINT IF EXISTS pending_session_invites_session_id_phone_e164_key;

-- Add the wider constraint
ALTER TABLE public.pending_session_invites
  ADD CONSTRAINT pending_session_invites_session_inviter_phone_key
  UNIQUE (session_id, inviter_id, phone_e164);


-- ═══════════════════════════════════════════════════════════
-- H1: Prevent concurrent board creation race condition
-- Add a UNIQUE partial index on collaboration_sessions.board_id (non-null only).
-- This ensures only one session can be assigned a given board, and more importantly,
-- the second concurrent UPDATE that tries to set board_id will fail rather than
-- silently overwrite. Combined with client-side .eq("status", "pending") optimistic
-- locking, this makes board creation fully safe.
-- ═══════════════════════════════════════════════════════════

CREATE UNIQUE INDEX IF NOT EXISTS idx_collaboration_sessions_unique_board
  ON public.collaboration_sessions (board_id)
  WHERE board_id IS NOT NULL;


-- ═══════════════════════════════════════════════════════════
-- M4: Add price_tiers column to board_session_preferences if missing
-- The app writes price_tiers on accept, but the column may not exist.
-- ═══════════════════════════════════════════════════════════

ALTER TABLE public.board_session_preferences
  ADD COLUMN IF NOT EXISTS price_tiers TEXT[] DEFAULT '{}';
