-- ORCH-0842 — Persist ticket PDFs to private storage so the buyer can view
-- the actual emailed PDF inside the consumer app.
--
-- New invariants codified by this ORCH:
--   I-PROPOSED-AK TICKET_PDF_FETCHABLE_BY_OWNER — only auth.uid() ==
--     orders.buyer_user_id may fetch a signed URL for that order's PDF.
--     Enforced by ticket-pdf-fetch edge function + CI gate.
--   I-PROPOSED-AL TICKET_PDF_SINGLE_SOURCE_OF_TRUTH — pdf-lib may be
--     imported ONLY from supabase/functions/_shared/ticketPdf.ts. Enforced
--     by CI gate.
--   I-PROPOSED-AM TICKET_PDF_STORAGE_BUCKET_PRIVATE — the ticket-pdfs
--     bucket has public = false and zero client-role policies on
--     storage.objects for it. Reads happen exclusively via signed URLs
--     issued by ticket-pdf-fetch after owner check; writes happen via
--     service-role from ticket-confirmation-dispatch and ticket-pdf-fetch
--     (lazy backfill). Service-role bypasses RLS, so no explicit policy
--     needed.

-- 1) Storage bucket — private; only signed URLs (60s TTL) issued by
-- ticket-pdf-fetch are allowed to read.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ticket-pdfs',
  'ticket-pdfs',
  false,
  6 * 1024 * 1024,  -- 6 MB cushion above the ticketPdf 5 MB cap
  ARRAY['application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- 2) Pointer column on orders so the fetch endpoint can short-circuit
-- head-check. Nullable because backfill happens lazily for pre-cutover
-- orders.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS ticket_pdf_path text;

COMMENT ON COLUMN public.orders.ticket_pdf_path IS
  'ORCH-0842: path within the private `ticket-pdfs` storage bucket where the rendered ticket PDF is stored (e.g. `tickets/<order_id>.pdf`). NULL until first successful upload; populated by `ticket-confirmation-dispatch` on send, or by `ticket-pdf-fetch` on lazy backfill. The PDF binary is generated by `supabase/functions/_shared/ticketPdf.ts` and MUST be byte-equivalent to the PDF attached to the buyer''s confirmation email. Per invariant I-PROPOSED-AL TICKET_PDF_SINGLE_SOURCE_OF_TRUTH no parallel renderer exists.';
